RATES=[('Acampo', 7.75, 'San Joaquin'),
 ('Acton', 8.75, 'Los Angeles'),
 ('Adelaida', 7.25, 'San Luis Obispo'),
 ('Adelanto', 7.75, 'San Bernardino'),
 ('Adin', 7.25, 'Modoc'),
 ('Agoura', 8.75, 'Los Angeles'),
 ('Agoura Hills', 8.75, 'Los Angeles'),
 ('Agua Caliente', 8.0, 'Sonoma'),
 ('Agua Caliente Springs', 7.75, 'San Diego'),
 ('Agua Dulce', 8.75, 'Los Angeles'),
 ('Aguanga', 7.75, 'Riverside'),
 ('Ahwahnee', 7.75, 'Madera'),
 ('Al Tahoe', 7.25, 'El Dorado'),
 ('Alameda', 8.75, 'Alameda'),
 ('Alamo', 8.25, 'Contra Costa'),
 ('Albany', 8.75, 'Alameda'),
 ('Alberhill', 7.75, 'Riverside'),
 ('Albion', 7.375, 'Mendocino'),
 ('Alderpoint', 7.25, 'Humboldt'),
 ('Alhambra', 8.75, 'Los Angeles'),
 ('Aliso Viejo', 7.75, 'Orange'),
 ('Alleghany', 7.25, 'Sierra'),
 ('Almaden Valley', 8.375, 'Santa Clara'),
 ('Almanor', 7.25, 'Plumas'),
 ('Almondale', 8.75, 'Los Angeles'),
 ('Alondra', 8.75, 'Los Angeles'),
 ('Alpaugh', 7.75, 'Tulare'),
 ('Alpine', 7.75, 'San Diego'),
 ('Alta', 7.25, 'Placer'),
 ('Alta Loma', 7.75, 'San Bernardino'),
 ('Altadena', 8.75, 'Los Angeles'),
 ('Altaville', 7.25, 'Calaveras'),
 ('Alton', 7.25, 'Humboldt'),
 ('Alturas', 7.25, 'Modoc'),
 ('Alviso', 8.375, 'Santa Clara'),
 ('Amador City', 7.75, 'Amador'),
 ('Amargosa', 7.75, 'Inyo'),
 ('Amboy', 7.75, 'San Bernardino'),
 ('American Canyon', 7.75, 'Napa'),
 ('Anaheim', 7.75, 'Orange'),
 ('Anderson', 7.25, 'Shasta'),
 ('Angels Camp', 7.25, 'Calaveras'),
 ('Angelus Oaks', 7.75, 'San Bernardino'),
 ('Angwin', 7.75, 'Napa'),
 ('Annapolis', 8.0, 'Sonoma'),
 ('Antelope', 7.75, 'Sacramento'),
 ('Antelope Acres', 8.75, 'Los Angeles'),
 ('Antioch', 8.25, 'Contra Costa'),
 ('Anza', 7.75, 'Riverside'),
 ('Apple Valley', 7.75, 'San Bernardino'),
 ('Applegate', 7.25, 'Placer'),
 ('Aptos', 8.0, 'Santa Cruz'),
 ('Arbuckle', 7.25, 'Colusa'),
 ('Arcadia', 8.75, 'Los Angeles'),
 ('Arcata', 8.0, 'Humboldt'),
 ('Argus', 7.75, 'San Bernardino'),
 ('Arleta', 8.75, 'Los Angeles'),
 ('Arlington', 7.75, 'Riverside'),
 ('Armona', 7.25, 'Kings'),
 ('Army Terminal', 8.75, 'Alameda'),
 ('Arnold', 7.25, 'Calaveras'),
 ('Aromas', 7.25, 'Monterey'),
 ('Arrowbear Lake', 7.75, 'San Bernardino'),
 ('Arrowhead Highlands', 7.75, 'San Bernardino'),
 ('Arroyo Grande', 7.75, 'San Luis Obispo'),
 ('Artesia', 8.75, 'Los Angeles'),
 ('Artois', 7.25, 'Glenn'),
 ('Arvin', 8.25, 'Kern'),
 ('Ashland', 8.75, 'Alameda'),
 ('Asti', 8.0, 'Sonoma'),
 ('Atascadero', 7.25, 'San Luis Obispo'),
 ('Athens', 8.75, 'Los Angeles'),
 ('Atherton', 8.25, 'San Mateo'),
 ('Atwater', 7.25, 'Merced'),
 ('Atwood', 7.75, 'Orange'),
 ('Auberry', 7.975, 'Fresno'),
 ('Auburn', 7.25, 'Placer'),
 ('Avalon', 9.25, 'Los Angeles'),
 ('Avenal', 7.25, 'Kings'),
 ('Avery', 7.25, 'Calaveras'),
 ('Avila Beach', 7.25, 'San Luis Obispo'),
 ('Azusa', 8.75, 'Los Angeles'),
 ('Badger', 7.75, 'Tulare'),
 ('Bailey', 8.75, 'Los Angeles'),
 ('Baker', 7.75, 'San Bernardino'),
 ('Bakersfield', 7.25, 'Kern'),
 ('Balboa', 7.75, 'Orange'),
 ('Balboa Island', 7.75, 'Orange'),
 ('Balboa Park', 7.75, 'San Diego'),
 ('Baldwin Park', 8.75, 'Los Angeles'),
 ('Ballard', 7.75, 'Santa Barbara'),
 ('Ballico', 7.25, 'Merced'),
 ('Ballroad', 7.75, 'Orange'),
 ('Bangor', 7.25, 'Butte'),
 ('Banning', 7.75, 'Riverside'),
 ('Banta', 7.75, 'San Joaquin'),
 ('Bard', 7.75, 'Imperial'),
 ('Barrington', 8.75, 'Los Angeles'),
 ('Barstow', 7.75, 'San Bernardino'),
 ('Bartlett', 7.75, 'Inyo'),
 ('Barton', 7.975, 'Fresno'),
 ('Base Line', 7.75, 'San Bernardino'),
 ('Bass Lake', 7.75, 'Madera'),
 ('Bassett', 8.75, 'Los Angeles'),
 ('Baxter', 7.25, 'Placer'),
 ('Bay Point', 8.25, 'Contra Costa'),
 ('Bayside', 7.25, 'Humboldt'),
 ('Baywood Park', 7.25, 'San Luis Obispo'),
 ('Beale A.F.B.', 7.25, 'Yuba'),
 ('Bear River Lake', 7.75, 'Amador'),
 ('Bear Valley', 7.25, 'Alpine'),
 ('Bear Valley', 7.75, 'Mariposa'),
 ('Beaumont', 7.75, 'Riverside'),
 ('Beckwourth', 7.25, 'Plumas'),
 ('Bel Air Estates', 8.75, 'Los Angeles'),
 ('Belden', 7.25, 'Plumas'),
 ('Bell Gardens', 8.75, 'Los Angeles'),
 ('Bell', 8.75, 'Los Angeles'),
 ('Bella Vista', 7.25, 'Shasta'),
 ('Bellflower', 8.75, 'Los Angeles'),
 ('Belmont', 8.25, 'San Mateo'),
 ('Belvedere', 8.0, 'Marin'),
 ('Ben Lomond', 8.0, 'Santa Cruz'),
 ('Benicia', 7.375, 'Solano'),
 ('Benton', 7.25, 'Mono'),
 ('Berkeley', 8.75, 'Alameda'),
 ('Bermuda Dunes', 7.75, 'Riverside'),
 ('Berry Creek', 7.25, 'Butte'),
 ('Bethel Island', 8.25, 'Contra Costa'),
 ('Betteravia', 7.75, 'Santa Barbara'),
 ('Beverly Hills', 8.75, 'Los Angeles'),
 ('Bieber', 7.25, 'Lassen'),
 ('Big Bar', 7.25, 'Trinity'),
 ('Big Basin', 8.0, 'Santa Cruz'),
 ('Big Bear City', 7.75, 'San Bernardino'),
 ('Big Bear Lake', 7.75, 'San Bernardino'),
 ('Big Bend', 7.25, 'Shasta'),
 ('Big Creek', 7.975, 'Fresno'),
 ('Big Oak Flat', 7.25, 'Tuolumne'),
 ('Big Pine', 7.75, 'Inyo'),
 ('Big River', 7.75, 'San Bernardino'),
 ('Big Sur', 7.25, 'Monterey'),
 ('Biggs', 7.25, 'Butte'),
 ('Bijou', 7.25, 'El Dorado'),
 ('Biola', 7.975, 'Fresno'),
 ('Biola College', 8.75, 'Los Angeles'),
 ('Birds Landing', 7.375, 'Solano'),
 ('Bishop', 7.75, 'Inyo'),
 ('Black Hawk', 8.25, 'Contra Costa'),
 ('Blairsden', 7.25, 'Plumas'),
 ('Blocksburg', 7.25, 'Humboldt'),
 ('Bloomington', 7.75, 'San Bernardino'),
 ('Blossom Hill', 8.375, 'Santa Clara'),
 ('Blossom Valley', 8.375, 'Santa Clara'),
 ('Blue Jay', 7.75, 'San Bernardino'),
 ('Blue Lake', 7.25, 'Humboldt'),
 ('Blythe', 7.75, 'Riverside'),
 ('Bodega', 8.0, 'Sonoma'),
 ('Bodega Bay', 8.0, 'Sonoma'),
 ('Bodfish', 7.25, 'Kern'),
 ('Bolinas', 8.0, 'Marin'),
 ('Bolsa', 7.75, 'Orange'),
 ('Bombay Beach', 7.75, 'Imperial'),
 ('Bonita', 7.75, 'San Diego'),
 ('Bonny Doon', 8.0, 'Santa Cruz'),
 ('Bonsall', 7.75, 'San Diego'),
 ('Boonville', 7.375, 'Mendocino'),
 ('Boron', 7.25, 'Kern'),
 ('Borrego Springs', 7.75, 'San Diego'),
 ('Bostonia', 7.75, 'San Diego'),
 ('Boulder Creek', 8.0, 'Santa Cruz'),
 ('Boulevard', 7.75, 'San Diego'),
 ('Bouquet Canyon', 8.75, 'Los Angeles'),
 ('Bowman', 7.25, 'Placer'),
 ('Boyes Hot Springs', 8.0, 'Sonoma'),
 ('Bradbury', 8.75, 'Los Angeles'),
 ('Bradford', 8.75, 'Alameda'),
 ('Bradley', 7.25, 'Monterey'),
 ('Branscomb', 7.375, 'Mendocino'),
 ('Brawley', 7.75, 'Imperial'),
 ('Brea', 7.75, 'Orange'),
 ('Brents Junction', 8.75, 'Los Angeles'),
 ('Brentwood', 8.75, 'Los Angeles'),
 ('Brentwood', 8.25, 'Contra Costa'),
 ('Briceland', 7.25, 'Humboldt'),
 ('Bridgeport', 7.75, 'Mariposa'),
 ('Bridgeport', 7.25, 'Mono'),
 ('Bridgeville', 7.25, 'Humboldt'),
 ('Brisbane', 8.25, 'San Mateo'),
 ('Broderick', 7.75, 'Yolo'),
 ('Brookdale', 8.0, 'Santa Cruz'),
 ('Brookhurst Center', 7.75, 'Orange'),
 ('Brooks', 7.25, 'Yolo'),
 ('Browns Valley', 7.25, 'Yuba'),
 ('Brownsville', 7.25, 'Yuba'),
 ('Bryn Mawr', 7.75, 'San Bernardino'),
 ('Bryte', 7.75, 'Yolo'),
 ('Buellton', 7.75, 'Santa Barbara'),
 ('Buena Park', 7.75, 'Orange'),
 ('Burbank', 8.75, 'Los Angeles'),
 ('Burlingame', 8.25, 'San Mateo'),
 ('Burney', 7.25, 'Shasta'),
 ('Burnt Ranch', 7.25, 'Trinity'),
 ('Burrel', 7.975, 'Fresno'),
 ('Burson', 7.25, 'Calaveras'),
 ('Butte City', 7.25, 'Glenn'),
 ('Butte Meadows', 7.25, 'Butte'),
 ('Buttonwillow', 7.25, 'Kern'),
 ('Byron', 8.25, 'Contra Costa'),
 ('Cabazon', 7.75, 'Riverside'),
 ('Cabrillo', 8.75, 'Los Angeles'),
 ('Cadiz', 7.75, 'San Bernardino'),
 ('Calabasas Highlands', 8.75, 'Los Angeles'),
 ('Calabasas Park', 8.75, 'Los Angeles'),
 ('Calabasas', 8.75, 'Los Angeles'),
 ('Calexico', 8.25, 'Imperial'),
 ('Caliente', 7.25, 'Kern'),
 ('California City', 7.25, 'Kern'),
 ('California Hot Springs', 7.75, 'Tulare'),
 ('California Valley', 7.25, 'San Luis Obispo'),
 ('Calimesa', 7.75, 'Riverside'),
 ('Calipatria', 7.75, 'Imperial'),
 ('Calistoga', 7.75, 'Napa'),
 ('Callahan', 7.25, 'Siskiyou'),
 ('Calpella', 7.375, 'Mendocino'),
 ('Calpine', 7.25, 'Sierra'),
 ('Calwa', 7.975, 'Fresno'),
 ('Camarillo', 7.25, 'Ventura'),
 ('Cambria', 7.25, 'San Luis Obispo'),
 ('Cambrian Park', 8.375, 'Santa Clara'),
 ('Cameron Park', 7.25, 'El Dorado'),
 ('Camino', 7.25, 'El Dorado'),
 ('Camp Beale', 7.25, 'Yuba'),
 ('Camp Connell', 7.25, 'Calaveras'),
 ('Camp Curry', 7.75, 'Mariposa'),
 ('Camp Kaweah', 7.75, 'Tulare'),
 ('Camp Meeker', 8.0, 'Sonoma'),
 ('Camp Nelson', 7.75, 'Tulare'),
 ('Camp Pendleton', 7.75, 'San Diego'),
 ('Camp Roberts', 7.25, 'Monterey'),
 ('Campbell', 8.625, 'Santa Clara'),
 ('Campo', 7.75, 'San Diego'),
 ('Campo Seco', 7.25, 'Calaveras'),
 ('Camptonville', 7.25, 'Yuba'),
 ('Canby', 7.25, 'Modoc'),
 ('Canoga Annex', 8.75, 'Los Angeles'),
 ('Canoga Park', 8.75, 'Los Angeles'),
 ('Cantil', 7.25, 'Kern'),
 ('Cantua Creek', 7.975, 'Fresno'),
 ('Canyon', 8.25, 'Contra Costa'),
 ('Canyon Country', 8.75, 'Los Angeles'),
 ('Canyon Lake', 7.75, 'Riverside'),
 ('Canyondam', 7.25, 'Plumas'),
 ('Capay', 7.25, 'Yolo'),
 ('Capistrano Beach', 7.75, 'Orange'),
 ('Capitola', 8.25, 'Santa Cruz'),
 ('Cardiff By The Sea', 7.75, 'San Diego'),
 ('Cardwell', 7.975, 'Fresno'),
 ('Carlotta', 7.25, 'Humboldt'),
 ('Carlsbad', 7.75, 'San Diego'),
 ('Carmel Rancho', 7.25, 'Monterey'),
 ('Carmel Valley', 7.25, 'Monterey'),
 ('Carmel', 7.25, 'Monterey'),
 ('Carmichael', 7.75, 'Sacramento'),
 ('Carnelian Bay', 7.25, 'Placer'),
 ('Carpinteria', 7.75, 'Santa Barbara'),
 ('Carson', 8.75, 'Los Angeles'),
 ('Cartago', 7.75, 'Inyo'),
 ('Caruthers', 7.975, 'Fresno'),
 ('Casitas Springs', 7.25, 'Ventura'),
 ('Casmalia', 7.75, 'Santa Barbara'),
 ('Caspar', 7.375, 'Mendocino'),
 ('Cassel', 7.25, 'Shasta'),
 ('Castaic', 8.75, 'Los Angeles'),
 ('Castella', 7.25, 'Shasta'),
 ('Castle A.F.B.', 7.25, 'Merced'),
 ('Castro Valley', 8.75, 'Alameda'),
 ('Castroville', 7.25, 'Monterey'),
 ('Cathedral City', 8.75, 'Riverside'),
 ('Catheys Valley', 7.75, 'Mariposa'),
 ('Cayucos', 7.25, 'San Luis Obispo'),
 ('Cazadero', 8.0, 'Sonoma'),
 ('Cecilville', 7.25, 'Siskiyou'),
 ('Cedar', 8.75, 'Los Angeles'),
 ('Cedar Crest', 7.975, 'Fresno'),
 ('Cedar Glen', 7.75, 'San Bernardino'),
 ('Cedar Ridge', 7.375, 'Nevada'),
 ('Cedarpines Park', 7.75, 'San Bernardino'),
 ('Cedarville', 7.25, 'Modoc'),
 ('Central Valley', 7.25, 'Shasta'),
 ('Century City', 8.75, 'Los Angeles'),
 ('Ceres', 7.875, 'Stanislaus'),
 ('Cerritos', 8.75, 'Los Angeles'),
 ('Challenge', 7.25, 'Yuba'),
 ('Chambers Lodge', 7.25, 'Placer'),
 ('Charter Oak', 8.75, 'Los Angeles'),
 ('Chatsworth', 8.75, 'Los Angeles'),
 ('Cherry Valley', 7.75, 'Riverside'),
 ('Chester', 7.25, 'Plumas'),
 ('Chicago Park', 7.375, 'Nevada'),
 ('Chico', 7.25, 'Butte'),
 ('Chilcoot', 7.25, 'Plumas'),
 ('China Lake NWC', 7.25, 'Kern'),
 ('Chinese Camp', 7.25, 'Tuolumne'),
 ('Chino Hills', 7.75, 'San Bernardino'),
 ('Chino', 7.75, 'San Bernardino'),
 ('Chiriaco Summit', 7.75, 'Riverside'),
 ('Cholame', 7.25, 'San Luis Obispo'),
 ('Chowchilla', 7.75, 'Madera'),
 ('Chualar', 7.25, 'Monterey'),
 ('Chula Vista', 7.75, 'San Diego'),
 ('Cima', 7.75, 'San Bernardino'),
 ('Citrus Heights', 7.75, 'Sacramento'),
 ('City of Commerce', 8.75, 'Los Angeles'),
 ('City of Industry', 8.75, 'Los Angeles'),
 ('City Terrace', 8.75, 'Los Angeles'),
 ('Claremont', 8.75, 'Los Angeles'),
 ('Clarksburg', 7.25, 'Yolo'),
 ('Clayton', 8.25, 'Contra Costa'),
 ('Clear Creek', 7.25, 'Siskiyou'),
 ('Clearlake Highlands', 7.75, 'Lake'),
 ('Clearlake Oaks', 7.25, 'Lake'),
 ('Clearlake Park', 7.75, 'Lake'),
 ('Clearlake', 7.75, 'Lake'),
 ('Clements', 7.75, 'San Joaquin'),
 ('Clinter', 7.975, 'Fresno'),
 ('Clio', 7.25, 'Plumas'),
 ('Clipper Mills', 7.25, 'Butte'),
 ('Cloverdale', 8.0, 'Sonoma'),
 ('Clovis', 7.975, 'Fresno'),
 ('Coachella', 7.75, 'Riverside'),
 ('Coalinga', 7.975, 'Fresno'),
 ('Coarsegold', 7.75, 'Madera'),
 ('Cobb', 7.25, 'Lake'),
 ('Cohasset', 7.25, 'Butte'),
 ('Cole', 8.75, 'Los Angeles'),
 ('Coleville', 7.25, 'Mono'),
 ('Colfax', 7.25, 'Placer'),
 ('College City', 7.25, 'Colusa'),
 ('College Grove Center', 7.75, 'San Diego'),
 ('Colma', 8.25, 'San Mateo'),
 ('Coloma', 7.25, 'El Dorado'),
 ('Colorado', 7.75, 'Mariposa'),
 ('Colton', 7.75, 'San Bernardino'),
 ('Columbia', 7.25, 'Tuolumne'),
 ('Colusa', 7.25, 'Colusa'),
 ('Commerce', 8.75, 'Los Angeles'),
 ('Comptche', 7.375, 'Mendocino'),
 ('Compton', 8.75, 'Los Angeles'),
 ('Concord', 8.75, 'Contra Costa'),
 ('Cool', 7.25, 'El Dorado'),
 ('Copperopolis', 7.25, 'Calaveras'),
 ('Corcoran', 7.25, 'Kings'),
 ('Cornell', 8.75, 'Los Angeles'),
 ('Corning', 7.25, 'Tehama'),
 ('Corona Del Mar', 7.75, 'Orange'),
 ('Corona', 7.75, 'Riverside'),
 ('Coronado', 7.75, 'San Diego'),
 ('Corralitos', 8.0, 'Santa Cruz'),
 ('Corte Madera', 8.0, 'Marin'),
 ('Coso Junction', 7.75, 'Inyo'),
 ('Costa Mesa', 7.75, 'Orange'),
 ('Cotati', 8.5, 'Sonoma'),
 ('Cottonwood', 7.25, 'Shasta'),
 ('Coulterville', 7.75, 'Mariposa'),
 ('Courtland', 7.75, 'Sacramento'),
 ('Covelo', 7.375, 'Mendocino'),
 ('Covina', 8.75, 'Los Angeles'),
 ('Cowan Heights', 7.75, 'Orange'),
 ('Coyote', 8.375, 'Santa Clara'),
 ('Crannell', 7.25, 'Humboldt'),
 ('Crenshaw', 8.75, 'Los Angeles'),
 ('Crescent City', 7.25, 'Del Norte'),
 ('Crescent Mills', 7.25, 'Plumas'),
 ('Cressey', 7.25, 'Merced'),
 ('Crest Park', 7.75, 'San Bernardino'),
 ('Cresta Blanca', 8.75, 'Alameda'),
 ('Crestline', 7.75, 'San Bernardino'),
 ('Creston', 7.25, 'San Luis Obispo'),
 ('Crockett', 8.25, 'Contra Costa'),
 ('Cromberg', 7.25, 'Plumas'),
 ('Cross Roads', 7.75, 'San Bernardino'),
 ('Crowley Lake', 7.25, 'Mono'),
 ('Crows Landing', 7.375, 'Stanislaus'),
 ('Cucamonga', 7.75, 'San Bernardino'),
 ('Cudahy', 8.75, 'Los Angeles'),
 ('Culver City', 8.75, 'Los Angeles'),
 ('Cummings', 7.375, 'Mendocino'),
 ('Cupertino', 8.375, 'Santa Clara'),
 ('Curry Village', 7.75, 'Mariposa'),
 ('Cutler', 7.75, 'Tulare'),
 ('Cutten', 7.25, 'Humboldt'),
 ('Cuyama', 7.75, 'Santa Barbara'),
 ('Cypress', 7.75, 'Orange '),
 ('Daggett', 7.75, 'San Bernardino'),
 ('Dairy Farm', 7.375, 'Solano'),
 ('Daly City', 8.25, 'San Mateo'),
 ('Dana Point', 7.75, 'Orange'),
 ('Danville', 8.25, 'Contra Costa'),
 ('Dardanelle', 7.25, 'Tuolumne'),
 ('Darwin', 7.75, 'Inyo'),
 ('Davenport', 8.0, 'Santa Cruz'),
 ('Davis Creek', 7.25, 'Modoc'),
 ('Davis* Davis campus rate is', 7.75, 'Yolo'),
 ('Death Valley', 7.75, 'Inyo'),
 ('Death Valley Junction', 7.75, 'Inyo'),
 ('Deer Park', 7.75, 'Napa'),
 ('Del Kern', 7.25, 'Kern'),
 ('Del Mar Heights', 7.75, 'San Luis Obispo'),
 ('Del Mar', 7.75, 'San Diego'),
 ('Del Monte Park', 7.25, 'Monterey'),
 ('Del Rey', 7.975, 'Fresno'),
 ('Del Rey Oaks', 8.25, 'Monterey'),
 ('Del Rosa', 7.75, 'San Bernardino'),
 ('Del Sur', 8.75, 'Los Angeles'),
 ('Delano', 8.25, 'Kern'),
 ('Deleven', 7.25, 'Colusa'),
 ('Delhi', 7.25, 'Merced'),
 ('Denair', 7.375, 'Stanislaus'),
 ('Denny', 7.25, 'Trinity'),
 ('Descanso', 7.75, 'San Diego'),
 ('Desert Center', 7.75, 'Riverside'),
 ('Desert Hot Springs', 7.75, 'Riverside'),
 ('Di Giorgio', 7.25, 'Kern'),
 ('Diablo', 8.25, 'Contra Costa'),
 ('Diamond Bar', 8.75, 'Los Angeles'),
 ('Diamond Springs', 7.25, 'El Dorado'),
 ('Dillon Beach', 8.0, 'Marin'),
 ('Dinkey Creek', 7.975, 'Fresno'),
 ('Dinuba', 8.5, 'Tulare'),
 ('Discovery Bay', 8.25, 'Contra Costa'),
 ('Dixon', 7.375, 'Solano'),
 ('Dobbins', 7.25, 'Yuba'),
 ('Dogtown', 8.0, 'Marin'),
 ('Dollar Ranch', 8.25, 'Contra Costa'),
 ('Dorris', 7.25, 'Siskiyou'),
 ('Dos Palos', 7.25, 'Merced'),
 ('Dos Rios', 7.375, 'Mendocino'),
 ('Douglas City', 7.25, 'Trinity'),
 ('Douglas Flat', 7.25, 'Calaveras'),
 ('Downey', 8.75, 'Los Angeles'),
 ('Downieville', 7.25, 'Sierra'),
 ('Doyle', 7.25, 'Lassen'),
 ('Drytown', 7.75, 'Amador'),
 ('Duarte', 8.75, 'Los Angeles'),
 ('Dublin', 8.75, 'Alameda'),
 ('Ducor', 7.75, 'Tulare'),
 ('Dulzura', 7.75, 'San Diego'),
 ('Duncans Mills', 8.0, 'Sonoma'),
 ('Dunlap', 7.975, 'Fresno'),
 ('Dunnigan', 7.25, 'Yolo'),
 ('Dunsmuir', 7.25, 'Siskiyou'),
 ('Durham', 7.25, 'Butte'),
 ('Dutch Flat', 7.25, 'Placer'),
 ('Eagle Mountain', 7.75, 'Riverside'),
 ('Eagle Rock', 8.75, 'Los Angeles'),
 ('Eagleville', 7.25, 'Modoc'),
 ('Earlimart', 7.75, 'Tulare'),
 ('Earp', 7.75, 'San Bernardino'),
 ('East Highlands', 7.75, 'San Bernardino'),
 ('East Irvine', 7.75, 'Orange'),
 ('East Los Angeles', 8.75, 'Los Angeles'),
 ('East Lynwood', 8.75, 'Los Angeles'),
 ('East Nicolaus', 7.25, 'Sutter'),
 ('East Palo Alto', 8.25, 'San Mateo'),
 ('East Porterville', 7.75, 'Tulare'),
 ('East Rancho Dominguez', 8.75, 'Los Angeles'),
 ('East San Pedro', 8.75, 'Los Angeles'),
 ('Eastgate', 8.75, 'Los Angeles'),
 ('Easton', 7.975, 'Fresno'),
 ('Eastside', 7.75, 'San Bernardino'),
 ('Eastvale', 7.75, 'Riverside'),
 ('Echo Lake', 7.25, 'El Dorado'),
 ('Echo Park', 8.75, 'Los Angeles'),
 ('Edgemont', 7.75, 'Riverside'),
 ('Edgewood', 7.25, 'Siskiyou'),
 ('Edison', 7.25, 'Kern'),
 ('Edwards', 7.25, 'Kern'),
 ('Edwards A.F.B.', 7.25, 'Kern'),
 ('El Cajon', 8.75, 'San Diego'),
 ('El Centro', 7.75, 'Imperial'),
 ('El Cerrito', 9.25, 'Contra Costa'),
 ('El Dorado', 7.25, 'El Dorado'),
 ('El Dorado Hills', 7.25, 'El Dorado'),
 ('El Granada', 8.25, 'San Mateo'),
 ('El Macero', 7.25, 'Yolo'),
 ('El Modena', 7.75, 'Orange'),
 ('El Monte', 9.25, 'Los Angeles'),
 ('El Nido', 7.25, 'Merced'),
 ('El Portal', 7.75, 'Mariposa'),
 ('El Segundo', 8.75, 'Los Angeles'),
 ('El Sobrante', 8.25, 'Contra Costa'),
 ('El Toro', 7.75, 'Orange'),
 ('El Toro M.C.A.S.', 7.75, 'Orange'),
 ('El Verano', 8.0, 'Sonoma'),
 ('El Viejo', 7.375, 'Stanislaus'),
 ('Eldridge', 8.0, 'Sonoma'),
 ('Elizabeth Lake', 8.75, 'Los Angeles'),
 ('Elk', 7.375, 'Mendocino'),
 ('Elk Creek', 7.25, 'Glenn'),
 ('Elk Grove', 7.75, 'Sacramento'),
 ('Elmira', 7.375, 'Solano'),
 ('Elmwood', 8.75, 'Alameda'),
 ('Elverta', 7.75, 'Sacramento'),
 ('Emerald Hills', 8.25, 'San Mateo'),
 ('Emeryville', 8.75, 'Alameda'),
 ('Emigrant Gap', 7.25, 'Placer'),
 ('Empire', 7.375, 'Stanislaus'),
 ('Encinitas', 7.75, 'San Diego'),
 ('Encino', 8.75, 'Los Angeles'),
 ('Enterprise', 7.25, 'Shasta'),
 ('Escalon', 7.75, 'San Joaquin'),
 ('Escondido', 7.75, 'San Diego'),
 ('Esparto', 7.25, 'Yolo'),
 ('Essex', 7.75, 'San Bernardino'),
 ('Etiwanda', 7.75, 'San Bernardino'),
 ('Etna', 7.25, 'Siskiyou'),
 ('Ettersburg', 7.25, 'Humboldt'),
 ('Eureka', 8.0, 'Humboldt'),
 ('Exeter', 7.75, 'Tulare'),
 ('Fair Oaks', 7.75, 'Sacramento'),
 ('Fairfax', 8.5, 'Marin'),
 ('Fairfield', 7.375, 'Solano'),
 ('Fairmount', 8.25, 'Contra Costa'),
 ('Fall River Mills', 7.25, 'Shasta'),
 ('Fallbrook', 7.75, 'San Diego'),
 ('Fallbrook Junction', 7.75, 'San Diego'),
 ('Fallen Leaf', 7.25, 'El Dorado'),
 ('Fallon', 8.0, 'Marin'),
 ('Fancher', 7.975, 'Fresno'),
 ('Farmersville', 8.25, 'Tulare'),
 ('Farmington', 7.75, 'San Joaquin'),
 ('Fawnskin', 7.75, 'San Bernardino'),
 ('Feather Falls', 7.25, 'Butte'),
 ('Fellows', 7.25, 'Kern'),
 ('Felton', 8.0, 'Santa Cruz'),
 ('Fenner', 7.75, 'San Bernardino'),
 ('Fernbridge', 7.25, 'Humboldt'),
 ('Ferndale', 7.25, 'Humboldt'),
 ('Fiddletown', 7.75, 'Amador'),
 ('Fields Landing', 7.25, 'Humboldt'),
 ('Fig Garden Village', 7.975, 'Fresno'),
 ('Fillmore', 7.25, 'Ventura'),
 ('Finley', 7.25, 'Lake'),
 ('Firebaugh', 7.975, 'Fresno'),
 ('Fish Camp', 7.75, 'Mariposa'),
 ('Five Points', 7.975, 'Fresno'),
 ('Flinn Springs', 7.75, 'San Diego'),
 ('Flintridge', 8.75, 'Los Angeles'),
 ('Florence', 8.75, 'Los Angeles'),
 ('Floriston', 7.375, 'Nevada'),
 ('Flournoy', 7.25, 'Tehama'),
 ('Folsom', 7.75, 'Sacramento'),
 ('Fontana', 7.75, 'San Bernardino'),
 ('Foothill Ranch', 7.75, 'Orange'),
 ('Forbestown', 7.25, 'Butte'),
 ('Forest Falls', 7.75, 'San Bernardino'),
 ('Forest Glen', 7.25, 'Trinity'),
 ('Forest Knolls', 8.0, 'Marin'),
 ('Forest Park', 8.75, 'Los Angeles'),
 ('Forest Ranch', 7.25, 'Butte'),
 ('Foresthill', 7.25, 'Placer'),
 ('Forestville', 8.0, 'Sonoma'),
 ('Forks of Salmon', 7.25, 'Siskiyou'),
 ('Fort Bidwell', 7.25, 'Modoc'),
 ('Fort Bragg', 8.375, 'Mendocino'),
 ('Fort Dick', 7.25, 'Del Norte'),
 ('Fort Irwin', 7.75, 'San Bernardino'),
 ('Fort Jones', 7.25, 'Siskiyou'),
 ('Fort Ord', 7.25, 'Monterey'),
 ('Fort Seward', 7.25, 'Humboldt'),
 ('Fortuna', 7.25, 'Humboldt'),
 ('Foster City', 8.25, 'San Mateo'),
 ('Fountain Valley', 7.75, 'Orange'),
 ('Fowler', 7.975, 'Fresno'),
 ('Frazier Park', 7.25, 'Kern'),
 ('Freedom', 8.0, 'Santa Cruz'),
 ('Freedom', 8.25, 'Santa Cruz'),
 ('Freeport', 7.75, 'Sacramento'),
 ('Freestone', 8.0, 'Sonoma'),
 ('Fremont', 8.75, 'Alameda'),
 ('French Camp', 7.75, 'San Joaquin'),
 ('French Gulch', 7.25, 'Shasta'),
 ('Freshwater', 7.25, 'Humboldt'),
 ('Fresno', 7.975, 'Fresno'),
 ('Friant', 7.975, 'Fresno'),
 ('Friendly Valley', 8.75, 'Los Angeles'),
 ('Frontera', 7.75, 'Riverside'),
 ('Fullerton', 7.75, 'Orange'),
 ('Fulton', 8.0, 'Sonoma'),
 ('Galt', 8.25, 'Sacramento'),
 ('Garberville', 7.25, 'Humboldt'),
 ('Garden Grove', 7.75, 'Orange'),
 ('Garden Valley', 7.25, 'El Dorado'),
 ('Gardena', 8.75, 'Los Angeles'),
 ('Garey', 7.75, 'Santa Barbara'),
 ('Garnet', 7.75, 'Riverside'),
 ('Gasquet', 7.25, 'Del Norte'),
 ('Gaviota', 7.75, 'Santa Barbara'),
 ('Gazelle', 7.25, 'Siskiyou'),
 ('George A.F.B.', 7.75, 'San Bernardino'),
 ('Georgetown', 7.25, 'El Dorado'),
 ('Gerber', 7.25, 'Tehama'),
 ('Geyserville', 8.0, 'Sonoma'),
 ('Giant Forest', 7.75, 'Tulare'),
 ('Gillman Hot Springs', 7.75, 'Riverside'),
 ('Gilroy', 8.375, 'Santa Clara'),
 ('Glassell Park', 8.75, 'Los Angeles'),
 ('Glen Avon', 7.75, 'Riverside'),
 ('Glen Ellen', 8.0, 'Sonoma'),
 ('Glenburn', 7.25, 'Shasta'),
 ('Glencoe', 7.25, 'Calaveras'),
 ('Glendale', 8.75, 'Los Angeles'),
 ('Glendora', 8.75, 'Los Angeles'),
 ('Glenhaven', 7.25, 'Lake'),
 ('Glenn', 7.25, 'Glenn'),
 ('Glennville', 7.25, 'Kern'),
 ('Gold River', 7.75, 'Sacramento'),
 ('Gold Run', 7.25, 'Placer'),
 ('Golden Hills', 7.25, 'Kern'),
 ('Goleta', 7.75, 'Santa Barbara'),
 ('Gonzales', 7.25, 'Monterey'),
 ('Goodyears Bar', 7.25, 'Sierra'),
 ('Gorman', 8.75, 'Los Angeles'),
 ('Goshen', 7.75, 'Tulare'),
 ('Government Island', 8.75, 'Alameda'),
 ('Graeagle', 7.25, 'Plumas'),
 ('Granada Hills', 8.75, 'Los Angeles'),
 ('Grand Terrace', 7.75, 'San Bernardino'),
 ('Granite Bay', 7.25, 'Placer'),
 ('Grass Valley', 7.375, 'Nevada'),
 ('Graton', 8.0, 'Sonoma'),
 ('Green Valley', 8.75, 'Los Angeles'),
 ('Green Valley Lake', 7.75, 'San Bernardino'),
 ('Greenacres', 7.25, 'Kern'),
 ('Greenbrae', 8.0, 'Marin'),
 ('Greenfield', 8.25, 'Monterey'),
 ('Greenview', 7.25, 'Siskiyou'),
 ('Greenville', 7.25, 'Plumas'),
 ('Greenwood', 7.25, 'El Dorado'),
 ('Grenada', 7.25, 'Siskiyou'),
 ('Gridley', 7.25, 'Butte'),
 ('Grimes', 7.25, 'Colusa'),
 ('Grizzly Flats', 7.25, 'El Dorado'),
 ('Groveland', 7.25, 'Tuolumne'),
 ('Grover Beach', 7.75, 'San Luis Obispo'),
 ('Guadalupe', 7.75, 'Santa Barbara'),
 ('Gualala', 7.375, 'Mendocino'),
 ('Guasti', 7.75, 'San Bernardino'),
 ('Guatay', 7.75, 'San Diego'),
 ('Guerneville', 8.0, 'Sonoma'),
 ('Guinda', 7.25, 'Yolo'),
 ('Gustine', 7.75, 'Merced'),
 ('Hacienda Heights', 8.75, 'Los Angeles'),
 ('Halcyon', 7.25, 'San Luis Obispo'),
 ('Half Moon Bay', 8.25, 'San Mateo'),
 ('Hamilton A.F.B.', 8.5, 'Marin'),
 ('Hamilton City', 7.25, 'Glenn'),
 ('Hanford', 7.25, 'Kings'),
 ('Happy Camp', 7.25, 'Siskiyou'),
 ('Harbor City', 8.75, 'Los Angeles'),
 ('Harmony', 7.25, 'San Luis Obispo'),
 ('Harris', 7.25, 'Humboldt'),
 ('Hat Creek', 7.25, 'Shasta'),
 ('Hathaway Pines', 7.25, 'Calaveras'),
 ('Havasu Lake', 7.75, 'San Bernardino'),
 ('Hawaiian Gardens', 8.75, 'Los Angeles'),
 ('Hawthorne', 8.75, 'Los Angeles'),
 ('Hayfork', 7.25, 'Trinity'),
 ('Hayward', 8.75, 'Alameda'),
 ('Hazard', 8.75, 'Los Angeles'),
 ('Healdsburg', 8.0, 'Sonoma'),
 ('Heber', 7.75, 'Imperial'),
 ('Helena', 7.25, 'Trinity'),
 ('Helendale', 7.75, 'San Bernardino'),
 ('Helm', 7.975, 'Fresno'),
 ('Hemet', 7.75, 'Riverside'),
 ('Herald', 7.75, 'Sacramento'),
 ('Hercules', 8.75, 'Contra Costa'),
 ('Herlong', 7.25, 'Lassen'),
 ('Hermosa Beach', 8.75, 'Los Angeles'),
 ('Herndon', 7.975, 'Fresno'),
 ('Hesperia', 7.75, 'San Bernardino'),
 ('Heyer', 8.75, 'Alameda'),
 ('Hickman', 7.375, 'Stanislaus'),
 ('Hidden Hills', 8.75, 'Los Angeles'),
 ('Highgrove', 7.75, 'Riverside'),
 ('Highland Park', 8.75, 'Los Angeles'),
 ('Highland', 7.75, 'San Bernardino'),
 ('Highway City', 7.975, 'Fresno'),
 ('Hillcrest', 7.75, 'San Diego'),
 ('Hillsborough', 8.25, 'San Mateo'),
 ('Hillsdale', 8.5, 'San Mateo'),
 ('Hilmar', 7.25, 'Merced'),
 ('Hilt', 7.25, 'Siskiyou'),
 ('Hinkley', 7.75, 'San Bernardino'),
 ('Hobergs', 7.25, 'Lake'),
 ('Hollister', 8.25, 'San Benito'),
 ('Hollywood', 8.75, 'Los Angeles'),
 ('Holmes', 7.25, 'Humboldt'),
 ('Holt', 7.75, 'San Joaquin'),
 ('Holtville', 7.75, 'Imperial'),
 ('Holy City', 8.375, 'Santa Clara'),
 ('Homeland', 7.75, 'Riverside'),
 ('Homestead', 7.25, 'Kern'),
 ('Homestead', 7.75, 'Riverside'),
 ('Homewood', 7.25, 'Placer'),
 ('Honby', 8.75, 'Los Angeles'),
 ('Honeydew', 7.25, 'Humboldt'),
 ('Hood', 7.75, 'Sacramento'),
 ('Hoopa', 7.25, 'Humboldt'),
 ('Hope Valley', 7.25, 'Alpine'),
 ('Hopland', 7.375, 'Mendocino'),
 ('Hornbrook', 7.25, 'Siskiyou'),
 ('Hornitos', 7.75, 'Mariposa'),
 ('Horse Creek', 7.25, 'Siskiyou'),
 ('Horse Lake', 7.25, 'Lassen'),
 ('Hughson', 7.375, 'Stanislaus'),
 ('Hume', 7.975, 'Fresno'),
 ('Huntington', 7.75, 'Orange'),
 ('Huntington Beach', 7.75, 'Orange'),
 ('Huntington Lake', 7.975, 'Fresno'),
 ('Huntington Park', 8.75, 'Los Angeles'),
 ('Huron', 7.975, 'Fresno'),
 ('Hyampom', 7.25, 'Trinity'),
 ('Hyde Park', 8.75, 'Los Angeles'),
 ('Hydesville', 7.25, 'Humboldt'),
 ('Idria', 7.25, 'San Benito'),
 ('Idyllwild', 7.75, 'Riverside'),
 ('Ignacio', 8.5, 'Marin'),
 ('Igo', 7.25, 'Shasta'),
 ('Imola', 7.75, 'Napa'),
 ('Imperial Beach', 7.75, 'San Diego'),
 ('Imperial', 7.75, 'Imperial'),
 ('Independence', 7.75, 'Inyo'),
 ('Indian Wells', 7.75, 'Riverside'),
 ('Indio', 7.75, 'Riverside'),
 ('Industry', 8.75, 'Los Angeles'),
 ('Inglewood', 9.25, 'Los Angeles'),
 ('Inverness', 8.0, 'Marin'),
 ('Inyo', 7.75, 'Inyo'),
 ('Inyokern', 7.25, 'Kern'),
 ('Ione', 7.75, 'Amador'),
 ('Iowa Hill', 7.25, 'Placer'),
 ('Irvine', 7.75, 'Orange'),
 ('Irwindale', 8.75, 'Los Angeles'),
 ('Isla Vista', 7.75, 'Santa Barbara'),
 ('Island Mountain', 7.25, 'Trinity'),
 ('Isleton', 7.75, 'Sacramento'),
 ('Ivanhoe', 7.75, 'Tulare'),
 ('Ivanpah', 7.75, 'San Bernardino'),
 ('Jackson', 7.75, 'Amador'),
 ('Jacumba', 7.75, 'San Diego'),
 ('Jamacha', 7.75, 'San Diego'),
 ('Jamestown', 7.25, 'Tuolumne'),
 ('Jamul', 7.75, 'San Diego'),
 ('Janesville', 7.25, 'Lassen'),
 ('Jenner', 8.0, 'Sonoma'),
 ('Johannesburg', 7.25, 'Kern'),
 ('Johnsondale', 7.75, 'Tulare'),
 ('Johnstonville', 7.25, 'Lassen'),
 ('Johnstown', 7.75, 'San Diego'),
 ('Jolon', 7.25, 'Monterey'),
 ('Joshua Tree', 7.75, 'San Bernardino'),
 ('Julian', 7.75, 'San Diego'),
 ('Junction City', 7.25, 'Trinity'),
 ('June Lake', 7.25, 'Mono'),
 ('Juniper', 7.25, 'Lassen'),
 ('Jurupa Valley', 7.75, 'Riverside'),
 ('Kagel Canyon', 8.75, 'Los Angeles'),
 ('Kaweah', 7.75, 'Tulare'),
 ('Keddie', 7.25, 'Plumas'),
 ('Keeler', 7.75, 'Inyo'),
 ('Keene', 7.25, 'Kern'),
 ('Kelsey', 7.25, 'El Dorado'),
 ('Kelseyville', 7.25, 'Lake'),
 ('Kelso', 7.75, 'San Bernardino'),
 ('Kensington', 8.25, 'Contra Costa'),
 ('Kentfield', 8.0, 'Marin'),
 ('Kenwood', 8.0, 'Sonoma'),
 ('Kerman', 7.975, 'Fresno'),
 ('Kernville', 7.25, 'Kern'),
 ('Keswick', 7.25, 'Shasta'),
 ('Kettleman City', 7.25, 'Kings'),
 ('Keyes', 7.375, 'Stanislaus'),
 ('King City', 7.25, 'Monterey'),
 ('Kings Beach', 7.25, 'Placer'),
 ('Kings Canyon National Park', 7.75, 'Tulare'),
 ('Kingsburg', 7.975, 'Fresno'),
 ('Kinyon', 7.25, 'Siskiyou'),
 ('Kirkwood', 7.25, 'Alpine'),
 ('Kit Carson', 7.75, 'Amador'),
 ('Klamath', 7.25, 'Del Norte'),
 ('Klamath River', 7.25, 'Siskiyou'),
 ('Kneeland', 7.25, 'Humboldt'),
 ('Knights Ferry', 7.375, 'Stanislaus'),
 ('Knights Landing', 7.25, 'Yolo'),
 ('Knightsen', 8.25, 'Contra Costa'),
 ('Korbel', 7.25, 'Humboldt'),
 ('Korbel', 8.0, 'Sonoma'),
 ('Kyburz', 7.25, 'El Dorado'),
 ('L.A. Airport', 8.75, 'Los Angeles'),
 ('La Canada- Flintridge', 8.75, 'Los Angeles'),
 ('La Crescenta', 8.75, 'Los Angeles'),
 ('La Cresta Village', 7.25, 'Kern'),
 ('La Grange', 7.375, 'Stanislaus'),
 ('La Habra Heights', 8.75, 'Los Angeles'),
 ('La Habra', 8.25, 'Orange'),
 ('La Honda', 8.25, 'San Mateo'),
 ('La Jolla', 7.75, 'San Diego'),
 ('La Mesa', 8.5, 'San Diego'),
 ('La Mirada', 8.75, 'Los Angeles'),
 ('La Palma', 7.75, 'Orange'),
 ('La Porte', 7.25, 'Plumas'),
 ('La Puente', 8.75, 'Los Angeles'),
 ('La Quinta', 7.75, 'Riverside'),
 ('La Selva Beach', 8.0, 'Santa Cruz'),
 ('La Verne', 8.75, 'Los Angeles'),
 ('La Vina', 8.75, 'Los Angeles'),
 ('Ladera', 8.25, 'San Mateo'),
 ('Ladera Heights', 8.75, 'Los Angeles'),
 ('Ladera Ranch', 7.75, 'Orange'),
 ('Lafayette', 8.25, 'Contra Costa'),
 ('Laguna Beach', 7.75, 'Orange'),
 ('Laguna Hills', 7.75, 'Orange'),
 ('Laguna Niguel', 7.75, 'Orange'),
 ('Laguna Woods', 7.75, 'Orange'),
 ('Lagunitas', 8.0, 'Marin'),
 ('Lake Alpine', 7.25, 'Alpine'),
 ('Lake Arrowhead', 7.75, 'San Bernardino'),
 ('Lake City', 7.25, 'Modoc'),
 ('Lake City', 7.375, 'Nevada'),
 ('Lake Elsinore', 7.75, 'Riverside'),
 ('Lake Forest', 7.75, 'Orange'),
 ('Lake Hughes', 8.75, 'Los Angeles'),
 ('Lake Isabella', 7.25, 'Kern'),
 ('Lake Los Angeles', 8.75, 'Los Angeles'),
 ('Lake Mary', 7.25, 'Mono'),
 ('Lake San Marcos', 7.75, 'San Diego'),
 ('Lake Shastina', 7.25, 'Siskiyou'),
 ('Lake Sherwood', 7.25, 'Ventura'),
 ('Lakehead', 7.25, 'Shasta'),
 ('Lakeport', 7.75, 'Lake'),
 ('Lakeshore', 7.975, 'Fresno'),
 ('Lakeside', 7.75, 'San Diego'),
 ('Lakeview', 7.75, 'Riverside'),
 ('Lakeview Terrace', 8.75, 'Los Angeles'),
 ('Lakewood', 8.75, 'Los Angeles'),
 ('Lamont', 7.25, 'Kern'),
 ('Lancaster', 8.75, 'Los Angeles'),
 ('Landers', 7.75, 'San Bernardino'),
 ('Landscape', 8.75, 'Alameda'),
 ('Lang', 8.75, 'Los Angeles'),
 ('Larkfield', 8.0, 'Sonoma'),
 ('Larkspur', 8.0, 'Marin'),
 ('Larwin Plaza', 7.375, 'Solano'),
 ('Lathrop', 7.75, 'San Joaquin'),
 ('Laton', 7.975, 'Fresno'),
 ('Lawndale', 8.75, 'Los Angeles'),
 ('Laws', 7.75, 'Inyo'),
 ('Laytonville', 7.375, 'Mendocino'),
 ('Le Grand', 7.25, 'Merced'),
 ('Lebec', 7.25, 'Kern'),
 ('Lee Vining', 7.25, 'Mono'),
 ('Leggett', 7.375, 'Mendocino'),
 ('Leisure World', 7.75, 'Orange'),
 ('Leisure World', 7.75, 'Orange'),
 ('Lemon Grove', 7.75, 'San Diego'),
 ('Lemoncove', 7.75, 'Tulare'),
 ('Lemoore', 7.25, 'Kings'),
 ('Lennox', 8.75, 'Los Angeles'),
 ('Lenwood', 7.75, 'San Bernardino'),
 ('Leona Valley', 8.75, 'Los Angeles'),
 ('Leucadia', 7.75, 'San Diego'),
 ('Lewiston', 7.25, 'Trinity'),
 ('Liberty Farms', 7.375, 'Solano'),
 ('Likely', 7.25, 'Modoc'),
 ('Lincoln Acres', 7.75, 'San Diego'),
 ('Lincoln Heights', 8.75, 'Los Angeles'),
 ('Lincoln Village', 7.75, 'San Joaquin'),
 ('Lincoln', 7.25, 'Placer'),
 ('Linda', 7.25, 'Yuba'),
 ('Linden', 7.75, 'San Joaquin'),
 ('Lindsay', 7.75, 'Tulare'),
 ('Linnell', 7.75, 'Tulare'),
 ('Litchfield', 7.25, 'Lassen'),
 ('Little Lake', 7.75, 'Inyo'),
 ('Little Norway', 7.25, 'El Dorado'),
 ('Little Valley', 7.25, 'Lassen'),
 ('Littleriver', 7.375, 'Mendocino'),
 ('Littlerock Little', 8.75, 'Los Angeles'),
 ('Live Oak ', 8.0, 'Santa Cruz'),
 ('Live Oak', 7.25, 'Sutter'),
 ('Livermore', 8.75, 'Alameda'),
 ('Livingston', 7.25, 'Merced'),
 ('Llano', 8.75, 'Los Angeles'),
 ('Loch Lomond', 7.25, 'Lake'),
 ('Locke', 7.75, 'Sacramento'),
 ('Lockeford', 7.75, 'San Joaquin'),
 ('Lockheed', 8.0, 'Santa Cruz'),
 ('Lockwood', 7.25, 'Monterey'),
 ('Lodi', 7.75, 'San Joaquin'),
 ('Loleta', 7.25, 'Humboldt'),
 ('Loma Linda', 7.75, 'San Bernardino'),
 ('Loma Mar', 8.25, 'San Mateo'),
 ('Loma Rica', 7.25, 'Yuba'),
 ('Lomita', 8.75, 'Los Angeles'),
 ('Lompoc', 7.75, 'Santa Barbara'),
 ('London', 7.75, 'Tulare'),
 ('Lone Pine', 7.75, 'Inyo'),
 ('Long Barn', 7.25, 'Tuolumne'),
 ('Long Beach', 8.75, 'Los Angeles'),
 ('Longview', 8.75, 'Los Angeles'),
 ('Lookout', 7.25, 'Modoc'),
 ('Loomis', 7.25, 'Placer'),
 ('Lorre Estates', 8.375, 'Santa Clara'),
 ('Los Alamitos', 7.75, 'Orange'),
 ('Los Alamos', 7.75, 'Santa Barbara'),
 ('Los Altos Hills', 8.375, 'Santa Clara'),
 ('Los Altos', 8.375, 'Santa Clara'),
 ('Los Angeles', 8.75, 'Los Angeles'),
 ('Los Banos', 7.75, 'Merced'),
 ('Los Gatos', 8.375, 'Santa Clara'),
 ('Los Molinos', 7.25, 'Tehama'),
 ('Los Nietos', 8.75, 'Los Angeles'),
 ('Los Olivos', 7.75, 'Santa Barbara'),
 ('Los Osos', 7.25, 'San Luis Obispo'),
 ('Los Padres', 7.25, 'San Luis Obispo'),
 ('Los Serranos', 7.75, 'San Bernardino'),
 ('Lost Hills', 7.25, 'Kern'),
 ('Lost Lake', 7.75, 'Riverside'),
 ('Lotus', 7.25, 'El Dorado'),
 ('Lower Lake', 7.25, 'Lake'),
 ('Loyalton', 7.25, 'Sierra'),
 ('Lucerne', 7.25, 'Lake'),
 ('Lucerne Valley', 7.75, 'San Bernardino'),
 ('Lucia', 7.25, 'Monterey'),
 ('Ludlow', 7.75, 'San Bernardino'),
 ('Lugo', 8.75, 'Los Angeles'),
 ('Lynwood', 8.75, 'Los Angeles'),
 ('Lytle Creek', 7.75, 'San Bernardino'),
 ('Macdoel', 7.25, 'Siskiyou'),
 ('Maclay', 8.75, 'Los Angeles'),
 ('Mad River', 7.25, 'Trinity'),
 ('Madeline', 7.25, 'Lassen'),
 ('Madera', 7.75, 'Madera'),
 ('Madison', 7.25, 'Yolo'),
 ('Magalia', 7.25, 'Butte'),
 ('Malaga', 7.975, 'Fresno'),
 ('Malibu', 8.75, 'Los Angeles'),
 ('Mammoth Lakes', 7.75, 'Mono'),
 ('Manhattan Beach', 8.75, 'Los Angeles'),
 ('Manteca', 8.25, 'San Joaquin'),
 ('Manton', 7.25, 'Tehama'),
 ('Manzanita Lake', 7.25, 'Shasta'),
 ('Mar Vista', 8.75, 'Los Angeles'),
 ('Marcelina', 8.75, 'Los Angeles'),
 ('March A.F.B.', 7.75, 'Riverside'),
 ('Mare Island', 8.375, 'Solano'),
 ('Maricopa', 7.25, 'Kern'),
 ('Marin City', 8.0, 'Marin'),
 ('Marina Del Rey', 8.75, 'Los Angeles'),
 ('Marina', 8.25, 'Monterey'),
 ('Marine Corps', 7.75, 'San Bernardino'),
 ('Mariner', 7.75, 'Orange'),
 ('Mariposa', 7.75, 'Mariposa'),
 ('Markleeville', 7.25, 'Alpine'),
 ('Marsh Manor', 8.25, 'San Mateo'),
 ('Marshall', 8.0, 'Marin'),
 ('Martell', 7.75, 'Amador'),
 ('Martinez', 8.25, 'Contra Costa'),
 ('Marysville', 7.25, 'Yuba'),
 ('Mather', 7.25, 'Tuolumne'),
 ('Mather ', 7.75, 'Sacramento'),
 ('Maxwell', 7.25, 'Colusa'),
 ('Maywood', 8.75, 'Los Angeles'),
 ('McArthur', 7.25, 'Shasta'),
 ('McClellan', 7.75, 'Sacramento'),
 ('McCloud', 7.25, 'Siskiyou'),
 ('McFarland', 7.25, 'Kern'),
 ('McKinleyville', 7.25, 'Humboldt'),
 ('McKittrick', 7.25, 'Kern'),
 ('Mead Valley', 7.75, 'Riverside'),
 ('Meadow Valley', 7.25, 'Plumas'),
 ('Meadow Vista', 7.25, 'Placer'),
 ('Meadowbrook', 7.75, 'Riverside'),
 ('Mecca', 7.75, 'Riverside'),
 ('Meeks Bay', 7.25, 'El Dorado'),
 ('Meiners Oaks', 7.25, 'Ventura'),
 ('Mendocino', 7.375, 'Mendocino'),
 ('Mendota', 7.975, 'Fresno'),
 ('Menifee', 7.75, 'Riverside'),
 ('Menlo Park', 8.25, 'San Mateo'),
 ('Mentone', 7.75, 'San Bernardino'),
 ('Merced', 7.75, 'Merced'),
 ('Meridian', 7.25, 'Sutter'),
 ('Mettler', 7.25, 'Kern'),
 ('Meyers', 7.25, 'El Dorado'),
 ('Middletown', 7.25, 'Lake'),
 ('Midland', 7.75, 'Riverside'),
 ('Midpines', 7.75, 'Mariposa'),
 ('Midway City', 7.75, 'Orange'),
 ('Milford', 7.25, 'Lassen'),
 ('Mill Creek', 7.25, 'Tehama'),
 ('Mill Valley', 8.0, 'Marin'),
 ('Millbrae', 8.25, 'San Mateo'),
 ('Millville', 7.25, 'Shasta'),
 ('Milpitas', 8.375, 'Santa Clara'),
 ('Mineral', 7.25, 'Tehama'),
 ('Mineral King', 7.75, 'Tulare'),
 ('Mint Canyon', 8.75, 'Los Angeles'),
 ('Mira Loma', 7.75, 'Riverside'),
 ('Mira Vista', 8.25, 'Contra Costa'),
 ('Miracle Hot Springs', 7.25, 'Kern'),
 ('Miramar', 7.75, 'San Diego'),
 ('Miramonte', 7.975, 'Fresno'),
 ('Miranda', 7.25, 'Humboldt'),
 ('Mission Hills', 8.75, 'Los Angeles'),
 ('Mission Viejo', 7.75, 'Orange'),
 ('Mi-Wuk Village', 7.25, 'Tuolumne'),
 ('Moccasin', 7.25, 'Tuolumne'),
 ('Modesto', 7.375, 'Stanislaus'),
 ('Moffett Field', 8.375, 'Santa Clara'),
 ('Mojave', 7.25, 'Kern'),
 ('Mokelumne Hill', 7.25, 'Calaveras'),
 ('Monarch Beach', 7.75, 'Orange'),
 ('Moneta', 8.75, 'Los Angeles'),
 ('Mono Hot Springs', 7.975, 'Fresno'),
 ('Mono Lake', 7.25, 'Mono'),
 ('Monolith', 7.25, 'Kern'),
 ('Monrovia', 8.75, 'Los Angeles'),
 ('Monta Vista', 8.375, 'Santa Clara'),
 ('Montague', 7.25, 'Siskiyou'),
 ('Montalvo', 7.25, 'Ventura'),
 ('Montara', 8.25, 'San Mateo'),
 ('Montclair', 8.0, 'San Bernardino'),
 ('Monte Rio', 8.0, 'Sonoma'),
 ('Monte Sereno', 8.375, 'Santa Clara'),
 ('Montebello', 8.75, 'Los Angeles'),
 ('Montecito', 7.75, 'Santa Barbara'),
 ('Monterey Bay Academy', 8.0, 'Santa Cruz'),
 ('Monterey Park', 8.75, 'Los Angeles'),
 ('Monterey', 7.25, 'Monterey'),
 ('Montgomery Creek', 7.25, 'Shasta'),
 ('Montrose', 8.75, 'Los Angeles'),
 ('Mooney', 7.75, 'Tulare'),
 ('Moonridge', 7.75, 'San Bernardino'),
 ('Moorpark', 7.25, 'Ventura'),
 ('Moraga', 8.25, 'Contra Costa'),
 ('Moreno Valley', 7.75, 'Riverside'),
 ('Morgan Hill', 8.375, 'Santa Clara'),
 ('Morongo Valley', 7.75, 'San Bernardino'),
 ('Morro Bay', 7.75, 'San Luis Obispo'),
 ('Morro Plaza', 7.25, 'San Luis Obispo'),
 ('Moss Beach', 8.25, 'San Mateo'),
 ('Moss Landing', 7.25, 'Monterey'),
 ('Mount Hamilton', 8.375, 'Santa Clara'),
 ('Mount Hebron', 7.25, 'Siskiyou'),
 ('Mount Hermon', 8.0, 'Santa Cruz'),
 ('Mount Laguna', 7.75, 'San Diego'),
 ('Mount Shasta', 7.5, 'Siskiyou'),
 ('Mount Wilson', 8.75, 'Los Angeles'),
 ('Mountain Center', 7.75, 'Riverside'),
 ('Mountain Mesa', 7.25, 'Kern'),
 ('Mountain Pass', 7.75, 'San Bernardino'),
 ('Mountain Ranch', 7.25, 'Calaveras'),
 ('Mountain View', 8.375, 'Santa Clara'),
 ('Mt. Aukum', 7.25, 'El Dorado'),
 ('Mt. Baldy', 7.75, 'San Bernardino'),
 ('Murphys', 7.25, 'Calaveras'),
 ('Murrieta', 7.75, 'Riverside'),
 ('Muscoy', 7.75, 'San Bernardino'),
 ('Myers Flat', 7.25, 'Humboldt'),
 ('Napa', 7.75, 'Napa'),
 ('Naples', 8.75, 'Los Angeles'),
 ('Nashville', 7.25, 'El Dorado'),
 ('National City', 8.75, 'San Diego'),
 ('Naval', 7.75, 'Ventura'),
 ('Naval', 7.75, 'San Diego'),
 ('Naval Air Station', 8.75, 'Alameda'),
 ('Naval Air Station', 7.75, 'San Diego'),
 ('Naval Air Station', 7.25, 'Kings'),
 ('Naval Hospital', 8.75, 'Alameda'),
 ('Naval Hospital', 7.75, 'San Diego'),
 ('Naval Supply Center', 8.75, 'Alameda'),
 ('Naval Training Center', 7.75, 'San Diego'),
 ('Navarro', 7.375, 'Mendocino'),
 ('Needles', 7.75, 'San Bernardino'),
 ('Nelson', 7.25, 'Butte'),
 ('Nevada City', 7.875, 'Nevada'),
 ('New Almaden', 8.375, 'Santa Clara'),
 ('New Cuyama', 7.75, 'Santa Barbara'),
 ('New Idria', 7.25, 'San Benito'),
 ('Newark', 8.75, 'Alameda'),
 ('Newberry', 7.75, 'San Bernardino'),
 ('Newberry Springs', 7.75, 'San Bernardino'),
 ('Newbury Park', 7.25, 'Ventura'),
 ('Newcastle', 7.25, 'Placer'),
 ('Newhall', 8.75, 'Los Angeles'),
 ('Newman', 7.375, 'Stanislaus'),
 ('Newport Beach', 7.75, 'Orange'),
 ('Nicasio', 8.0, 'Marin'),
 ('Nice', 7.25, 'Lake'),
 ('Nicolaus', 7.25, 'Sutter'),
 ('Niland', 7.75, 'Imperial'),
 ('Nipomo', 7.25, 'San Luis Obispo'),
 ('Nipton', 7.75, 'San Bernardino'),
 ('Norco', 7.75, 'Riverside'),
 ('Norden', 7.375, 'Nevada'),
 ('North Edwards', 7.25, 'Kern'),
 ('North Fork', 7.75, 'Madera'),
 ('North Gardena', 8.75, 'Los Angeles'),
 ('North Highlands', 7.75, 'Sacramento'),
 ('North Hills', 8.75, 'Los Angeles'),
 ('North Hollywood', 8.75, 'Los Angeles'),
 ('North Palm Springs', 7.75, 'Riverside'),
 ('North San Juan', 7.375, 'Nevada'),
 ('North Shore', 7.75, 'Riverside'),
 ('Northridge', 8.75, 'Los Angeles'),
 ('Norton A.F.B.', 8.0, 'San Bernardino'),
 ('Norwalk', 8.75, 'Los Angeles'),
 ('Novato', 8.5, 'Marin'),
 ('Nubieber', 7.25, 'Lassen'),
 ('Nuevo', 7.75, 'Riverside'),
 ('Nyeland Acres', 7.25, 'Ventura'),
 ('Oak Park', 7.25, 'Ventura'),
 ('Oak Run', 7.25, 'Shasta'),
 ('Oak View', 7.25, 'Ventura'),
 ('Oakdale', 7.875, 'Stanislaus'),
 ('Oakhurst', 7.75, 'Madera'),
 ('Oakland', 8.75, 'Alameda'),
 ('Oakley', 8.25, 'Contra Costa'),
 ('Oakville', 7.75, 'Napa'),
 ('Oasis', 7.75, 'Riverside'),
 ('Oban', 8.75, 'Los Angeles'),
 ("O'Brien", 7.25, 'Shasta'),
 ('Occidental', 8.0, 'Sonoma'),
 ('Oceano', 7.25, 'San Luis Obispo'),
 ('Oceanside', 7.75, 'San Diego'),
 ('Ocotillo', 7.75, 'Imperial'),
 ('Ocotillo Wells', 7.75, 'San Diego'),
 ('Oildale', 7.25, 'Kern'),
 ('Ojai', 7.25, 'Ventura'),
 ('Olancha', 7.75, 'Inyo'),
 ('Old Station', 7.25, 'Shasta'),
 ('Olema', 8.0, 'Marin'),
 ('Olinda', 7.25, 'Shasta'),
 ('Olive View', 8.75, 'Los Angeles'),
 ('Olivehurst', 7.25, 'Yuba'),
 ('Olivenhain', 7.75, 'San Diego'),
 ('Olympic Valley', 7.25, 'Placer'),
 ('Omo Ranch', 7.25, 'El Dorado'),
 ("O'Neals", 7.75, 'Madera'),
 ('Ono', 7.25, 'Shasta'),
 ('Ontario', 7.75, 'San Bernardino'),
 ('Onyx', 7.25, 'Kern'),
 ('Opal Cliffs', 8.0, 'Santa Cruz'),
 ('Orange Cove', 7.975, 'Fresno'),
 ('Orange', 7.75, 'Orange'),
 ('Orangevale', 7.75, 'Sacramento'),
 ('Orcutt', 7.75, 'Santa Barbara'),
 ('Ordbend', 7.25, 'Glenn'),
 ('Oregon House', 7.25, 'Yuba'),
 ('Orick', 7.25, 'Humboldt'),
 ('Orinda', 8.25, 'Contra Costa'),
 ('Orland', 7.25, 'Glenn'),
 ('Orleans', 7.25, 'Humboldt'),
 ('Oro Grande', 7.75, 'San Bernardino'),
 ('Orosi', 7.75, 'Tulare'),
 ('Oroville', 7.25, 'Butte'),
 ('Otay', 7.75, 'San Diego'),
 ('Oxnard', 7.75, 'Ventura'),
 ('Pacheco', 8.25, 'Contra Costa'),
 ('Pacific Grove', 8.25, 'Monterey'),
 ('Pacific House', 7.25, 'El Dorado'),
 ('Pacific Palisades', 8.75, 'Los Angeles'),
 ('Pacifica', 8.25, 'San Mateo'),
 ('Pacoima', 8.75, 'Los Angeles'),
 ('Paicines', 7.25, 'San Benito'),
 ('Pajaro', 7.25, 'Monterey'),
 ('Pala', 7.75, 'San Diego'),
 ('Palermo', 7.25, 'Butte'),
 ('Pallett', 8.75, 'Los Angeles'),
 ('Palm City', 7.75, 'Riverside'),
 ('Palm City', 7.75, 'San Diego'),
 ('Palm Desert', 7.75, 'Riverside'),
 ('Palm Springs', 8.75, 'Riverside'),
 ('Palmdale', 8.75, 'Los Angeles'),
 ('Palo Alto', 8.375, 'Santa Clara'),
 ('Palo Cedro', 7.25, 'Shasta'),
 ('Palo Verde', 7.75, 'Imperial'),
 ('Palomar Mountain', 7.75, 'San Diego'),
 ('Palos Verdes Estates', 8.75, 'Los Angeles'),
 ('Palos Verdes/Peninsula', 8.75, 'Los Angeles'),
 ('Panorama City', 8.75, 'Los Angeles'),
 ('Paradise', 7.25, 'Butte'),
 ('Paramount', 8.75, 'Los Angeles'),
 ('Parker Dam', 7.75, 'San Bernardino'),
 ('Parkfield', 7.25, 'Monterey'),
 ('Parlier', 7.975, 'Fresno'),
 ('Pasadena', 8.75, 'Los Angeles'),
 ('Paskenta', 7.25, 'Tehama'),
 ('Paso Robles', 7.25, 'San Luis Obispo'),
 ('Patterson', 7.375, 'Stanislaus'),
 ('Patton', 7.75, 'San Bernardino'),
 ('Pauma Valley', 7.75, 'San Diego'),
 ('Paynes Creek', 7.25, 'Tehama'),
 ('Pearblossom', 8.75, 'Los Angeles'),
 ('Pearland', 8.75, 'Los Angeles'),
 ('Pebble Beach', 7.25, 'Monterey'),
 ('Pedley', 7.75, 'Riverside'),
 ('Peninsula Village', 7.25, 'Plumas'),
 ('Penn Valley', 7.375, 'Nevada'),
 ('Penngrove', 8.0, 'Sonoma'),
 ('Penryn', 7.25, 'Placer'),
 ('Pepperwood', 7.25, 'Humboldt'),
 ('Permanente', 8.375, 'Santa Clara'),
 ('Perris', 7.75, 'Riverside'),
 ('Perry', 8.75, 'Los Angeles'),
 ('Pescadero', 8.25, 'San Mateo'),
 ('Petaluma', 8.0, 'Sonoma'),
 ('Petrolia', 7.25, 'Humboldt'),
 ('Phelan', 7.75, 'San Bernardino'),
 ('Phillipsville', 7.25, 'Humboldt'),
 ('Philo', 7.375, 'Mendocino'),
 ('Pico Rivera', 9.75, 'Los Angeles'),
 ('Piedmont', 8.75, 'Alameda'),
 ('Piedra', 7.975, 'Fresno'),
 ('Piercy', 7.375, 'Mendocino'),
 ('Pilot Hill', 7.25, 'El Dorado'),
 ('Pine Grove', 7.75, 'Amador'),
 ('Pine Valley', 7.75, 'San Diego'),
 ('Pinecrest', 7.25, 'Tuolumne'),
 ('Pinedale', 7.975, 'Fresno'),
 ('Pinetree', 8.75, 'Los Angeles'),
 ('Pinole', 8.75, 'Contra Costa'),
 ('Pinon Hills', 7.75, 'San Bernardino'),
 ('Pioneer', 7.75, 'Amador'),
 ('Pioneertown', 7.75, 'San Bernardino'),
 ('Piru', 7.25, 'Ventura'),
 ('Pismo Beach', 7.75, 'San Luis Obispo'),
 ('Pittsburg', 8.75, 'Contra Costa'),
 ('Pixley', 7.75, 'Tulare'),
 ('Placentia', 7.75, 'Orange'),
 ('Placerville', 7.75, 'El Dorado'),
 ('Plainview', 7.75, 'Tulare'),
 ('Planada', 7.25, 'Merced'),
 ('Plaster City', 7.75, 'Imperial'),
 ('Platina', 7.25, 'Shasta'),
 ('Playa Del Rey', 8.75, 'Los Angeles'),
 ('Pleasant Grove', 7.25, 'Sutter'),
 ('Pleasant Hill', 8.25, 'Contra Costa'),
 ('Pleasanton', 8.75, 'Alameda'),
 ('Plymouth', 7.75, 'Amador'),
 ('Point Arena', 7.875, 'Mendocino'),
 ('Point Mugu', 7.25, 'Ventura'),
 ('Point Pittsburg', 8.25, 'Contra Costa'),
 ('Point Reyes Station', 8.0, 'Marin'),
 ('Pollock Pines', 7.25, 'El Dorado'),
 ('Pomona', 8.75, 'Los Angeles'),
 ('Pond', 7.25, 'Kern'),
 ('Pondosa', 7.25, 'Siskiyou'),
 ('Pope Valley', 7.75, 'Napa'),
 ('Poplar', 7.75, 'Tulare'),
 ('Port Costa', 8.25, 'Contra Costa'),
 ('Port Hueneme', 7.75, 'Ventura'),
 ('Porter Ranch', 8.75, 'Los Angeles'),
 ('Porterville', 8.25, 'Tulare'),
 ('Portola Valley', 8.25, 'San Mateo'),
 ('Portola', 7.25, 'Plumas'),
 ('Portuguese Bend Palos', 8.75, 'Los Angeles'),
 ('Posey', 7.75, 'Tulare'),
 ('Potrero', 7.75, 'San Diego'),
 ('Potter Valley', 7.375, 'Mendocino'),
 ('Poway', 7.75, 'San Diego'),
 ('Prather', 7.975, 'Fresno'),
 ('Presidio', 8.5, 'San Francisco'),
 ('Presidio of Monterey', 7.25, 'Monterey'),
 ('Priest Valley', 7.25, 'Monterey'),
 ('Princeton', 7.25, 'Colusa'),
 ('Proberta', 7.25, 'Tehama'),
 ('Project City', 7.25, 'Shasta'),
 ('Prunedale', 7.25, 'Monterey'),
 ('Pt. Dume', 8.75, 'Los Angeles'),
 ('Pulga', 7.25, 'Butte'),
 ('Pumpkin Center', 7.25, 'Kern'),
 ('Quail Valley', 7.75, 'Riverside'),
 ('Quartz Hill', 8.75, 'Los Angeles'),
 ('Quincy', 7.25, 'Plumas'),
 ('Rackerby', 7.25, 'Yuba'),
 ('Rail Road Flat', 7.25, 'Calaveras'),
 ('Rainbow', 7.75, 'San Diego'),
 ('Raisin City', 7.975, 'Fresno'),
 ('Ramona', 7.75, 'San Diego'),
 ('Ranchita', 7.75, 'San Diego'),
 ('Rancho Bernardo', 7.75, 'San Diego'),
 ('Rancho California', 7.75, 'Riverside'),
 ('Rancho Cordova* ', 7.75, 'Sacramento'),
 ('Rancho Cucamonga', 7.75, 'San Bernardino'),
 ('Rancho Dominguez', 8.75, 'Los Angeles'),
 ('Rancho Mirage', 7.75, 'Riverside'),
 ('Rancho Murieta', 7.75, 'Sacramento'),
 ('Rancho Palos Verdes', 8.75, 'Los Angeles'),
 ('Rancho Park', 8.75, 'Los Angeles'),
 ('Rancho Santa Fe', 7.75, 'San Diego'),
 ('Rancho Santa Margarita', 7.75, 'Orange'),
 ('Randsburg', 7.25, 'Kern'),
 ('Ravendale', 7.25, 'Lassen'),
 ('Ravenna', 8.75, 'Los Angeles'),
 ('Raymond', 7.75, 'Madera'),
 ('Red Bluff', 7.25, 'Tehama'),
 ('Red Mountain', 7.75, 'San Bernardino'),
 ('Red Top', 7.75, 'Madera'),
 ('Redcrest', 7.25, 'Humboldt'),
 ('Redding', 7.25, 'Shasta'),
 ('Redlands', 7.75, 'San Bernardino'),
 ('Redondo Beach', 8.75, 'Los Angeles'),
 ('Redway', 7.25, 'Humboldt'),
 ('Redwood City', 8.25, 'San Mateo'),
 ('Redwood Estates', 8.375, 'Santa Clara'),
 ('Redwood Valley', 7.375, 'Mendocino'),
 ('Reedley', 8.475, 'Fresno'),
 ('Refugio Beach', 7.75, 'Santa Barbara'),
 ('Represa', 7.75, 'Sacramento'),
 ('Requa', 7.25, 'Del Norte'),
 ('Rescue', 7.25, 'El Dorado'),
 ('Reseda', 8.75, 'Los Angeles'),
 ('Rheem Valley', 8.25, 'Contra Costa'),
 ('Rialto', 7.75, 'San Bernardino'),
 ('Richardson Grove', 7.25, 'Humboldt'),
 ('Richardson Springs', 7.25, 'Butte'),
 ('Richfield', 7.25, 'Tehama'),
 ('Richgrove', 7.75, 'Tulare'),
 ('Richmond', 8.75, 'Contra Costa'),
 ('Richvale', 7.25, 'Butte'),
 ('Ridgecrest', 8.0, 'Kern'),
 ('Rimforest', 7.75, 'San Bernardino'),
 ('Rimpau', 8.75, 'Los Angeles'),
 ('Rio Bravo', 7.25, 'Kern'),
 ('Rio Del Mar', 8.0, 'Santa Cruz'),
 ('Rio Dell', 7.25, 'Humboldt'),
 ('Rio Linda', 7.75, 'Sacramento'),
 ('Rio Nido', 8.0, 'Sonoma'),
 ('Rio Oso', 7.25, 'Sutter'),
 ('Rio Vista', 7.375, 'Solano'),
 ('Ripley', 7.75, 'Riverside'),
 ('Ripon', 7.75, 'San Joaquin'),
 ('River Pines', 7.75, 'Amador'),
 ('Riverbank', 7.375, 'Stanislaus'),
 ('Riverdale', 7.975, 'Fresno'),
 ('Riverside', 7.75, 'Riverside'),
 ('Robbins', 7.25, 'Sutter'),
 ('Rocklin', 7.25, 'Placer'),
 ('Rodeo', 8.25, 'Contra Costa'),
 ('Rohnert Park', 8.5, 'Sonoma'),
 ('Rohnerville', 7.25, 'Humboldt'),
 ('Rolling Hills Estates', 8.75, 'Los Angeles'),
 ('Rolling Hills', 8.75, 'Los Angeles'),
 ('Romoland', 7.75, 'Riverside'),
 ('Rosamond', 7.25, 'Kern'),
 ('Rose Bowl', 8.75, 'Los Angeles'),
 ('Roseland', 8.0, 'Sonoma'),
 ('Rosemead', 8.75, 'Los Angeles'),
 ('Roseville', 7.25, 'Placer'),
 ('Ross', 8.0, 'Marin'),
 ('Rossmoor', 7.75, 'Orange'),
 ('Rough and Ready', 7.375, 'Nevada'),
 ('Round Mountain', 7.25, 'Shasta'),
 ('Rowland Heights', 8.75, 'Los Angeles'),
 ('Royal Oaks', 7.25, 'Monterey'),
 ('Rubidoux', 7.75, 'Riverside'),
 ('Ruby Valley', 7.25, 'Humboldt'),
 ('Rumsey', 7.25, 'Yolo'),
 ('Running Springs', 7.75, 'San Bernardino'),
 ('Ruth', 7.25, 'Trinity'),
 ('Rutherford', 7.75, 'Napa'),
 ('Ryde', 7.75, 'Sacramento'),
 ('Sacramento', 7.75, 'Sacramento'),
 ('Saint Helena', 7.75, 'Napa'),
 ('Salida', 7.375, 'Stanislaus'),
 ('Salinas', 7.75, 'Monterey'),
 ('Salton City', 7.75, 'Imperial'),
 ('Salyer', 7.25, 'Trinity'),
 ('Samoa', 7.25, 'Humboldt'),
 ('San Andreas', 7.25, 'Calaveras'),
 ('San Anselmo', 8.0, 'Marin'),
 ('San Ardo', 7.25, 'Monterey'),
 ('San Benito', 7.25, 'San Benito'),
 ('San Bernardino', 8.0, 'San Bernardino'),
 ('San Bruno', 8.25, 'San Mateo'),
 ('San Carlos', 8.25, 'San Mateo'),
 ('San Clemente', 7.75, 'Orange'),
 ('San Diego', 7.75, 'San Diego'),
 ('San Dimas', 8.75, 'Los Angeles'),
 ('San Fernando', 8.75, 'Los Angeles'),
 ('San Francisco', 8.5, 'San Francisco'),
 ('San Gabriel', 8.75, 'Los Angeles'),
 ('San Geronimo', 8.0, 'Marin'),
 ('San Gregorio', 8.25, 'San Mateo'),
 ('San Jacinto', 7.75, 'Riverside'),
 ('San Joaquin', 7.975, 'Fresno'),
 ('San Jose', 8.375, 'Santa Clara'),
 ('San Juan Bautista', 8.0, 'San Benito'),
 ('San Juan Capistrano', 7.75, 'Orange'),
 ('San Juan Plaza Juan', 7.75, 'Orange'),
 ('San Leandro', 9.0, 'Alameda'),
 ('San Lorenzo', 8.75, 'Alameda'),
 ('San Lucas', 7.25, 'Monterey'),
 ('San Luis Obispo', 7.75, 'San Luis Obispo'),
 ('San Luis Rey', 7.75, 'San Diego'),
 ('San Marcos', 7.75, 'San Diego'),
 ('San Marino', 8.75, 'Los Angeles'),
 ('San Martin', 8.375, 'Santa Clara'),
 ('San Mateo', 8.5, 'San Mateo'),
 ('San Miguel', 7.25, 'San Luis Obispo'),
 ('San Pablo', 8.75, 'Contra Costa'),
 ('San Pedro', 8.75, 'Los Angeles'),
 ('San Quentin', 8.0, 'Marin'),
 ('San Rafael', 8.5, 'Marin'),
 ('San Ramon', 8.25, 'Contra Costa'),
 ('San Simeon', 7.25, 'San Luis Obispo'),
 ('San Tomas', 8.375, 'Santa Clara'),
 ('San Ysidro', 7.75, 'San Diego'),
 ('Sand City', 7.75, 'Monterey'),
 ('Sanger', 8.725, 'Fresno'),
 ('Santa Ana', 7.75, 'Orange'),
 ('Santa Barbara', 7.75, 'Santa Barbara'),
 ('Santa Clara', 8.375, 'Santa Clara'),
 ('Santa Clarita', 8.75, 'Los Angeles'),
 ('Santa Cruz', 8.5, 'Santa Cruz'),
 ('Santa Fe Springs', 8.75, 'Los Angeles'),
 ('Santa Margarita', 7.25, 'San Luis Obispo'),
 ('Santa Maria', 8.0, 'Santa Barbara'),
 ('Santa Monica', 9.25, 'Los Angeles'),
 ('Santa Nella', 7.25, 'Merced'),
 ('Santa Paula', 7.25, 'Ventura'),
 ('Santa Rita Park', 7.25, 'Merced'),
 ('Santa Rosa', 8.5, 'Sonoma'),
 ('Santa Rosa Valley', 7.25, 'Ventura'),
 ('Santa Ynez', 7.75, 'Santa Barbara'),
 ('Santa Ysabel', 7.75, 'San Diego'),
 ('Santee', 7.75, 'San Diego'),
 ('Saratoga', 8.375, 'Santa Clara'),
 ('Saticoy', 7.25, 'Ventura'),
 ('Sattley', 7.25, 'Sierra'),
 ('Saugus', 8.75, 'Los Angeles'),
 ('Sausalito', 8.0, 'Marin'),
 ('Sawtelle', 8.75, 'Los Angeles'),
 ('Sawyers Bar', 7.25, 'Siskiyou'),
 ('Scotia', 7.25, 'Humboldt'),
 ('Scott Bar', 7.25, 'Siskiyou'),
 ('Scotts Valley', 8.0, 'Santa Cruz'),
 ('Sea Ranch', 8.0, 'Sonoma'),
 ('Seabright', 8.5, 'Santa Cruz'),
 ('Seal Beach', 7.75, 'Orange'),
 ('Seaside', 8.25, 'Monterey'),
 ('Sebastopol', 8.25, 'Sonoma'),
 ('Seeley', 7.75, 'Imperial'),
 ('Seiad Valley', 7.25, 'Siskiyou'),
 ('Selby', 8.25, 'Contra Costa'),
 ('Selma', 8.475, 'Fresno'),
 ('Seminole Hot Springs', 8.75, 'Los Angeles'),
 ('Sepulveda', 8.75, 'Los Angeles'),
 ('Sequoia National Park', 7.75, 'Tulare'),
 ('Shafter', 7.25, 'Kern'),
 ('Shandon', 7.25, 'San Luis Obispo'),
 ('Sharpe Army Depot', 7.75, 'San Joaquin'),
 ('Shasta', 7.25, 'Shasta'),
 ('Shasta Lake', 7.25, 'Shasta'),
 ('Shaver Lake', 7.975, 'Fresno'),
 ('Sheepranch', 7.25, 'Calaveras'),
 ('Shell Beach', 7.75, 'San Luis Obispo'),
 ('Sheridan', 7.25, 'Placer'),
 ('Sherman Island', 7.75, 'Sacramento'),
 ('Sherman Oaks', 8.75, 'Los Angeles'),
 ('Sherwin Plaza', 7.25, 'Mono'),
 ('Shingle Springs', 7.25, 'El Dorado'),
 ('Shingletown', 7.25, 'Shasta'),
 ('Shively', 7.25, 'Humboldt'),
 ('Shore Acres', 8.25, 'Contra Costa'),
 ('Shoshone', 7.75, 'Inyo'),
 ('Sierra City', 7.25, 'Sierra'),
 ('Sierra Madre', 8.75, 'Los Angeles'),
 ('Sierraville', 7.25, 'Sierra'),
 ('Signal Hill', 8.75, 'Los Angeles'),
 ('Silver Lake', 7.75, 'Amador'),
 ('Silverado Canyon', 7.75, 'Orange'),
 ('Simi Valley', 7.25, 'Ventura'),
 ('Sisquoc', 7.75, 'Santa Barbara'),
 ('Sites', 7.25, 'Colusa'),
 ('Sky Valley', 7.75, 'Riverside'),
 ('Skyforest', 7.75, 'San Bernardino'),
 ('Sleepy Valley', 8.75, 'Los Angeles'),
 ('Sloat', 7.25, 'Plumas'),
 ('Sloughhouse', 7.75, 'Sacramento'),
 ('Smartsville', 7.25, 'Yuba'),
 ('Smith River', 7.25, 'Del Norte'),
 ('Smithflat', 7.25, 'El Dorado'),
 ('Smoke Tree', 8.75, 'Riverside'),
 ('Smoke Tree', 7.75, 'San Bernardino'),
 ('Snelling', 7.25, 'Merced'),
 ('Soda Springs', 7.375, 'Nevada'),
 ('Solana Beach', 7.75, 'San Diego'),
 ('Soledad', 8.25, 'Monterey'),
 ('Solemint', 8.75, 'Los Angeles'),
 ('Solvang', 7.75, 'Santa Barbara'),
 ('Somerset', 7.25, 'El Dorado'),
 ('Somes Bar', 7.25, 'Siskiyou'),
 ('Somis', 7.25, 'Ventura'),
 ('Sonoma', 8.5, 'Sonoma'),
 ('Sonora', 7.75, 'Tuolumne'),
 ('Soquel', 8.0, 'Santa Cruz'),
 ('Soulsbyville', 7.25, 'Tuolumne'),
 ('South Dos Palos', 7.25, 'Merced'),
 ('South El Monte', 9.25, 'Los Angeles'),
 ('South Fork', 7.25, 'Humboldt'),
 ('South Gate', 9.75, 'Los Angeles'),
 ('South Laguna', 7.75, 'Orange'),
 ('South Lake Tahoe', 7.75, 'El Dorado'),
 ('South Pasadena', 8.75, 'Los Angeles'),
 ('South San Francisco', 8.25, 'San Mateo'),
 ('South Shore', 8.75, 'Alameda'),
 ('South Whittier', 8.75, 'Los Angeles'),
 ('Spanish Flat', 7.75, 'Napa'),
 ('Spreckels', 7.25, 'Monterey'),
 ('Spring Garden', 7.25, 'Plumas'),
 ('Spring Valley', 7.75, 'San Diego'),
 ('Springville', 7.75, 'Tulare'),
 ('Spyrock', 7.375, 'Mendocino'),
 ('Squaw Valley', 7.975, 'Fresno'),
 ('St. Helena', 7.75, 'Napa'),
 ('Standard', 7.25, 'Tuolumne'),
 ('Standish', 7.25, 'Lassen'),
 ('Stanford', 8.375, 'Santa Clara'),
 ('Stanislaus', 7.25, 'Tuolumne'),
 ('Stanton', 7.75, 'Orange'),
 ('Steele Park', 7.75, 'Napa'),
 ('Stevenson Ranch', 8.75, 'Los Angeles'),
 ('Stevinson', 7.25, 'Merced'),
 ('Stewarts Point', 8.0, 'Sonoma'),
 ('Stinson Beach', 8.0, 'Marin'),
 ('Stirling City', 7.25, 'Butte'),
 ('Stockton', 8.0, 'San Joaquin'),
 ('Stonyford', 7.25, 'Colusa'),
 ('Storrie', 7.25, 'Plumas'),
 ('Stratford', 7.25, 'Kings'),
 ('Strathmore', 7.75, 'Tulare'),
 ('Strawberry', 7.25, 'Tuolumne'),
 ('Strawberry Valley', 7.25, 'Yuba'),
 ('Studio City', 8.75, 'Los Angeles'),
 ('Sugarloaf', 7.75, 'San Bernardino'),
 ('Suisun City', 7.375, 'Solano'),
 ('Sulphur Springs', 8.75, 'Los Angeles'),
 ('Sultana', 7.75, 'Tulare'),
 ('Summerland', 7.75, 'Santa Barbara'),
 ('Summit', 7.75, 'San Bernardino'),
 ('Summit City', 7.25, 'Shasta'),
 ('Sun City', 7.75, 'Riverside'),
 ('Sun Valley', 8.75, 'Los Angeles'),
 ('Sunland', 8.75, 'Los Angeles'),
 ('Sunnymead', 7.75, 'Riverside'),
 ('Sunnyside', 7.75, 'San Diego'),
 ('Sunnyvale', 8.375, 'Santa Clara'),
 ('Sunol', 8.75, 'Alameda'),
 ('Sunset Beach', 7.75, 'Orange'),
 ('Sunset Whitney Ranch', 7.25, 'Placer'),
 ('Surfside', 7.75, 'Orange'),
 ('Susanville', 7.25, 'Lassen'),
 ('Sutter', 7.25, 'Sutter'),
 ('Sutter Creek', 7.75, 'Amador'),
 ('Swall Meadows', 7.75, 'Inyo'),
 ('Sylmar', 8.75, 'Los Angeles'),
 ('Taft', 7.25, 'Kern'),
 ('Tagus Ranch', 7.75, 'Tulare'),
 ('Tahoe City', 7.25, 'Placer'),
 ('Tahoe Paradise', 7.25, 'El Dorado'),
 ('Tahoe Valley', 7.25, 'El Dorado'),
 ('Tahoe Vista', 7.25, 'Placer'),
 ('Tahoma', 7.25, 'Placer'),
 ('Talmage', 7.375, 'Mendocino'),
 ('Tamal', 8.0, 'Marin'),
 ('Tarzana', 8.75, 'Los Angeles'),
 ('Taylorsville', 7.25, 'Plumas'),
 ('Tecate', 7.75, 'San Diego'),
 ('Tecopa', 7.75, 'Inyo'),
 ('Tehachapi', 7.25, 'Kern'),
 ('Tehama', 7.25, 'Tehama'),
 ('Temecula', 7.75, 'Riverside'),
 ('Temple City', 8.75, 'Los Angeles'),
 ('Templeton', 7.25, 'San Luis Obispo'),
 ('Terminal Island', 8.75, 'Los Angeles'),
 ('Termo', 7.25, 'Lassen'),
 ('Terra Bella', 7.75, 'Tulare'),
 ('Thermal', 7.75, 'Riverside'),
 ('Thornton', 7.75, 'San Joaquin'),
 ('Thousand Oaks', 7.25, 'Ventura'),
 ('Thousand Palms', 7.75, 'Riverside'),
 ('Three Rivers', 7.75, 'Tulare'),
 ('Tiburon', 8.0, 'Marin'),
 ('Tierra Del Sol', 7.75, 'San Diego'),
 ('Tierrasanta', 7.75, 'San Diego'),
 ('Tipton', 7.75, 'Tulare'),
 ('Tollhouse', 7.975, 'Fresno'),
 ('Toluca Lake', 8.75, 'Los Angeles'),
 ('Tomales', 8.0, 'Marin'),
 ('Toms Place', 7.25, 'Mono'),
 ('Topanga', 8.75, 'Los Angeles'),
 ('Topanga Park', 8.75, 'Los Angeles'),
 ('Topaz', 7.25, 'Mono'),
 ('Torrance', 8.75, 'Los Angeles'),
 ('Town Center', 7.75, 'Tulare'),
 ('Trabuco Canyon', 7.75, 'Orange'),
 ('Tracy', 8.25, 'San Joaquin'),
 ('Tranquillity', 7.975, 'Fresno'),
 ('Traver', 7.75, 'Tulare'),
 ('Travis A.F.B.', 7.375, 'Solano'),
 ('Tres Pinos', 7.25, 'San Benito'),
 ('Trinidad', 8.0, 'Humboldt'),
 ('Trinity Center', 7.25, 'Trinity'),
 ('Trona', 7.75, 'San Bernardino'),
 ('Trowbridge', 7.25, 'Sutter'),
 ('Truckee', 7.875, 'Nevada'),
 ('Tujunga', 8.75, 'Los Angeles'),
 ('Tulare', 8.25, 'Tulare'),
 ('Tulelake', 7.25, 'Siskiyou'),
 ('Tuolumne', 7.25, 'Tuolumne'),
 ('Tuolumne Meadows', 7.75, 'Mariposa'),
 ('Tupman', 7.25, 'Kern'),
 ('Turlock', 7.375, 'Stanislaus'),
 ('Tustin', 7.75, 'Orange'),
 ('Twain', 7.25, 'Plumas'),
 ('Twain Harte', 7.25, 'Tuolumne'),
 ('Twentynine Palms', 7.75, 'San Bernardino'),
 ('Twin Bridges', 7.25, 'El Dorado'),
 ('Twin Peaks', 7.75, 'San Bernardino'),
 ('Two Rock Coast Guard Station', 8.0, 'Sonoma'),
 ('U.S. Naval Postgrad School', 7.25, 'Monterey'),
 ('Ukiah', 7.875, 'Mendocino'),
 ('Union City', 9.25, 'Alameda'),
 ('Universal City', 8.75, 'Los Angeles'),
 ('University', 7.75, 'Santa Barbara'),
 ('University Park', 7.75, 'Orange'),
 ('Upland', 7.75, 'San Bernardino'),
 ('Upper Lake/ Upper Lake Valley', 7.25, 'Lake'),
 ('Vacaville', 7.375, 'Solano'),
 ('Val Verde Park', 8.75, 'Los Angeles'),
 ('Valencia', 8.75, 'Los Angeles'),
 ('Valinda', 8.75, 'Los Angeles'),
 ('Vallecito', 7.25, 'Calaveras'),
 ('Vallejo', 8.375, 'Solano'),
 ('Valley Center', 7.75, 'San Diego'),
 ('Valley Fair', 8.375, 'Santa Clara'),
 ('Valley Ford', 8.0, 'Sonoma'),
 ('Valley Home', 7.375, 'Stanislaus'),
 ('Valley Springs', 7.25, 'Calaveras'),
 ('Valley Village', 8.75, 'Los Angeles'),
 ('Valyermo', 8.75, 'Los Angeles'),
 ('Van Nuys', 8.75, 'Los Angeles'),
 ('Vandenberg A.F.B', 7.75, 'Santa Barbara'),
 ('Vasquez Rocks', 8.75, 'Los Angeles'),
 ('Venice', 8.75, 'Los Angeles'),
 ('Ventucopa', 7.75, 'Santa Barbara'),
 ('Ventura', 7.25, 'Ventura'),
 ('Verdugo City', 8.75, 'Los Angeles'),
 ('Vernalis', 7.75, 'San Joaquin'),
 ('Vernon', 8.75, 'Los Angeles'),
 ("Veteran's Hospital", 8.75, 'Los Angeles'),
 ('Victor', 7.75, 'San Joaquin'),
 ('Victorville', 7.75, 'San Bernardino'),
 ('Vidal', 7.75, 'San Bernardino'),
 ('View Park', 8.75, 'Los Angeles'),
 ('Villa Grande', 8.0, 'Sonoma'),
 ('Villa Park', 7.75, 'Orange'),
 ('Vina', 7.25, 'Tehama'),
 ('Vincent', 8.75, 'Los Angeles'),
 ('Vineburg', 8.0, 'Sonoma'),
 ('Vinton', 7.25, 'Plumas'),
 ('Virgilia', 7.25, 'Plumas'),
 ('Visalia', 8.0, 'Tulare'),
 ('Vista Park', 7.25, 'Kern'),
 ('Vista', 8.25, 'San Diego'),
 ('Volcano', 7.75, 'Amador'),
 ('Volta', 7.25, 'Merced'),
 ('Wallace', 7.25, 'Calaveras'),
 ('Walnut Creek', 8.25, 'Contra Costa'),
 ('Walnut Grove', 7.75, 'Sacramento'),
 ('Walnut Park', 8.75, 'Los Angeles'),
 ('Walnut', 8.75, 'Los Angeles'),
 ('Warm Springs', 8.75, 'Alameda'),
 ('Warner Springs', 7.75, 'San Diego'),
 ('Wasco', 7.25, 'Kern'),
 ('Waterford', 7.375, 'Stanislaus'),
 ('Watsonville', 8.25, 'Santa Cruz'),
 ('Watts', 8.75, 'Los Angeles'),
 ('Waukena', 7.75, 'Tulare'),
 ('Wawona', 7.75, 'Mariposa'),
 ('Weaverville', 7.25, 'Trinity'),
 ('Weed', 7.25, 'Siskiyou'),
 ('Weimar', 7.25, 'Placer'),
 ('Weldon', 7.25, 'Kern'),
 ('Wendel', 7.25, 'Lassen'),
 ('Weott', 7.25, 'Humboldt'),
 ('West Covina', 8.75, 'Los Angeles'),
 ('West Hills', 8.75, 'Los Angeles'),
 ('West Hollywood', 8.75, 'Los Angeles'),
 ('West Los Angeles', 8.75, 'Los Angeles'),
 ('West Pittsburg', 8.25, 'Contra Costa'),
 ('West Point', 7.25, 'Calaveras'),
 ('West Sacramento', 7.75, 'Yolo'),
 ('Westchester', 8.75, 'Los Angeles'),
 ('Westend', 7.75, 'San Bernardino'),
 ('Westhaven', 7.25, 'Humboldt'),
 ('Westlake', 8.75, 'Los Angeles'),
 ('Westlake Village', 7.25, 'Ventura'),
 ('Westlake Village', 8.75, 'Los Angeles'),
 ('Westley', 7.375, 'Stanislaus'),
 ('Westminster', 7.75, 'Orange'),
 ('Westmorland', 7.75, 'Imperial'),
 ('Westport', 7.375, 'Mendocino'),
 ('Westside', 7.375, 'Stanislaus'),
 ('Westwood', 7.25, 'Lassen'),
 ('Westwood', 8.75, 'Los Angeles'),
 ('Wheatland', 7.75, 'Yuba'),
 ('Wheeler Ridge', 7.25, 'Kern'),
 ('Whiskeytown', 7.25, 'Shasta'),
 ('Whispering Pines', 7.25, 'Lake'),
 ('White Pines', 7.25, 'Calaveras'),
 ('Whitethorn', 7.25, 'Humboldt'),
 ('Whitewater', 7.75, 'Riverside'),
 ('Whitlow', 7.25, 'Humboldt'),
 ('Whitmore', 7.25, 'Shasta'),
 ('Whittier', 8.75, 'Los Angeles'),
 ('Wildomar', 7.75, 'Riverside'),
 ('Wildwood', 7.25, 'Shasta'),
 ('Williams', 7.75, 'Colusa'),
 ('Willits', 7.875, 'Mendocino'),
 ('Willow Creek', 7.25, 'Humboldt'),
 ('Willow Ranch', 7.25, 'Modoc'),
 ('Willowbrook', 8.75, 'Los Angeles'),
 ('Willows', 7.25, 'Glenn'),
 ('Wilmington', 8.75, 'Los Angeles'),
 ('Wilseyville', 7.25, 'Calaveras'),
 ('Wilsona Gardens', 8.75, 'Los Angeles'),
 ('Wilton', 7.75, 'Sacramento'),
 ('Winchester', 7.75, 'Riverside'),
 ('Windsor Hills', 8.75, 'Los Angeles'),
 ('Windsor', 8.0, 'Sonoma'),
 ('Winnetka', 8.75, 'Los Angeles'),
 ('Winterhaven', 7.75, 'Imperial'),
 ('Winters', 7.25, 'Yolo'),
 ('Winton', 7.25, 'Merced'),
 ('Wishon', 7.75, 'Madera'),
 ('Witter Springs', 7.25, 'Lake'),
 ('Wofford Heights', 7.25, 'Kern'),
 ('Woodacre', 8.0, 'Marin'),
 ('Woodbridge', 7.75, 'San Joaquin'),
 ('Woodfords', 7.25, 'Alpine'),
 ('Woodlake', 7.75, 'Tulare'),
 ('Woodland', 8.0, 'Yolo'),
 ('Woodland Hills', 8.75, 'Los Angeles'),
 ('Woodleaf', 7.25, 'Yuba'),
 ('Woodside', 8.25, 'San Mateo'),
 ('Woodville', 7.75, 'Tulare'),
 ('Woody', 7.25, 'Kern'),
 ('Wrightwood', 7.75, 'San Bernardino'),
 ('Yankee Hill', 7.25, 'Butte'),
 ('Yermo', 7.75, 'San Bernardino'),
 ('Yettem', 7.75, 'Tulare'),
 ('Yolo', 7.25, 'Yolo'),
 ('Yorba Linda', 7.75, 'Orange'),
 ('Yorkville', 7.375, 'Mendocino'),
 ('Yosemite Lodge', 7.75, 'Mariposa'),
 ('Yosemite National Park', 7.75, 'Mariposa'),
 ('Yountville', 7.75, 'Napa'),
 ('Yreka', 7.25, 'Siskiyou'),
 ('Yuba City', 7.25, 'Sutter'),
 ('Yucaipa', 7.75, 'San Bernardino'),
 ('Yucca Valley', 7.75, 'San Bernardino'),
 ('Zamora', 7.25, 'Yolo'),
 ('Zenia', 7.25, 'Trinity')]
